app-qiskit.html

Update the "Tutorials" link on the landing page to point to the `stable` branch of the tutorials, as since the latest changes on the `tutorials` repo, that is the branch that is meant to work with the streamlined, pip-installable version of `qiskit`

Update nbviewer tutorial link to "stable" branch

---

src/components/page-terra.js

Update the code example on the Terra page to match `terra-0.6` code base.

Update terra example for version 0.6

---

src/components/app-shell.js
src/router.js

Link in local is a not found, because the web works a SPA and documentation is other app, but in production should be work fine.
Fixed #89

Remove target blank on documentation link

---

src/components/app-shell.js

Fix the tutorials link now that the name of `start_here` has been changed.

fix tutorials link

---

src/components/page-ignis.js

This commit corrects the misspelled "Ignis" in [Qiskit Ignis](https://qiskit.org/ignis) -> Stack

fixed typo in Ignis

---

deploy/deploy_cos.sh

This commit adds the qiskit api schemas (mainly qobj and backend
information) to the qiskit.org deploy script. This is just a stop gap
to start uploading. A follow up patch here will be to just add this
upload step to the qiskit-terra repo directly since the object store
means we don't have to (and shouldn't) centralize all the artifacts
hosted on the qiskit.org domain in a single massive git repo.
Fixes #48

Add schemas to the website

---

locales/en/app.json

Fix #297 
@CatherineKlauss it would be convenient to also review the `communityDescription`. These texts correspond with the following qiskit.org section:

Change Community title to refer to social media

---

components/footers/PageFooter.vue

Fixes #365
Because `/textbook` isn't handled by Nuxt it needs to be a standard `<a>`-tag to work.

Fix broken Textbook-Link

---

components/qiskit/QiskitElementPage.vue
components/qiskit/QiskitPage.vue
mixins/segment-analytics.ts
plugins/segment-analytics.ts

Closes #359
Abstract page components are convenient in this project to enforce all
pages to add the `routeName` property for tracking purposes, and `title`
and `description` for element-specific pages.
However, the Component decorator that comes with Nuxt is not ready for
decorating abstract classes. The `abstract` modifier is TypeScript
specific and has no impact during runtime. An abstract class is the same
as a regular class, from a JavaScript perspective. This PR augments the
TypeScript definition of Component to allow abstract classes to be
decorated.
It also introduces the interface `TrackedPage` which is implemented by
the `QiskitPage` page component so all the concrete descendants must
implement the requirements imposed by `TrackedPage`. In this case, the
existence of the …

[Issue 359] Enable applying Component decorator to abstract classes.

---

assets/scss/layout.scss

Fix #411 
As #411 explains, removing `overflow-x: hidden` makes iOS Safari to missbehave when there is overflowing content (such as the video in the Community > Eduction page) and allows the user to scroll hortizontally and reach the parts of the content indended to be hidden.
Nevertheless, this risk is lower than the existing one since our current data confirms most of the visits comes from desktop devices and linking to a section is a very common pattern in the web and should not break.

Remove overflow-x to solve the issue with scrollTo()

---

components/Footer.vue

Eventpages have a seperate footer, which has a copyright-notice including a year. 
This is currently hardcoded and shows "Copyright IBM Corp. 2018-2019".
Example: https://qiskit.org/events/camp-2020/
This PR updates the footer component to use dynamic year instead of just updating it to 2020.

Add Dynamic Year to Footer

---

assets/scss/mq.scss
pages/events/index.vue

Closes #426 
Make background video to load always asynchronous to not affect our web performance, force autoplay and prevent the whole video's header from rendering at all when the user is loading the page from a mobile device.

ISSUE-426 Fix video background in events page

---

assets/scss/theme.scss
components/cards/EventCard.vue
package-lock.json
package.json
pages/events/index.vue
plugins/carbon.ts

Closes #433 
To see the component in action go to https://qiskitorg-git-fork-y4izus-yg-event-card.qiskit.now.sh/events.
This is how it looks in different browsers:
- Firefox
- Chrome
- Safari

Event card for desktop

---

pages/aer.vue

Use NoiseModel.from_backend() to avoid deprecation warning

---

assets/scss/carbon/community-theme.scss
assets/scss/carbon/components.scss
components/ctas/Cta.vue
components/ctas/LegacyCta.vue
components/footers/FooterSubsection.vue
components/footers/LinkList.vue
components/footers/PageFooter.vue
components/headers/LegacyPresentation.vue
components/menus/QiskitOrgMenu.vue
components/qiskit/SoftwareStack.vue
components/qiskit/SyntaxHighlight.vue
components/sections/LegacySection.vue
nuxt.config.ts
pages/index.vue
plugins/carbon.ts
static/css/fonts.css

Fix #453
The PR does not try to use Carbon as intended, creating a correct type hierarchy but using those Carbon styles closest to how qiskit.org landing and element pages look right now to start using Carbon infrastructure.

Fix type-styles for the landing and element pages

---

components/cards/EventCard.vue
content/events/past-community-events.json

Removes event card arrow if the event hasn't web

---

content/education/textbook-toc.md
content/events/past-community-events.json
content/events/upcoming-community-events.json
hooks/event-conversion-utils.ts
jest.config.js
pages/events/index.vue
store/modules/events.ts
tests/hooks/event-conversion-utils.spec.ts
tests/store/events.spec.ts

Fix #518 
This PR also changes the state object of the store (to be a function) following Nux.js recommendation at:
https://nuxtjs.org/guide/vuex-store/#activate-the-store
> Regardless of the mode, your `state` value should **always be a `function`** to avoid unwanted shared state on the server side.

Allow filtering events with multiple types

---

hooks/event-conversion-utils.ts
pages/events/index.vue
store/modules/events.ts

The const pattern for using symbolic names instead of strings is useful for avoiding typos and taking advantage of coding tools so it is extended to world location values too.
However, its use with TS may introduce some unneeded repetition when trying to write the types with the string values the symbolic names try to represent:
```ts
const SYMBOLIC_NAMES = {
symbolA: 'Symbol A',
symbolB: 'Symbol B'
}
type Names = 'Symbol A'|'Symbol B'
```
This PR uses [`const` assertions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions) to derive the types from the const values.

Extend const symbolic pattern to world locations and derive types from these consts

---

content/education/textbook-toc.md
content/events/past-community-events.json
content/events/upcoming-community-events.json
hooks/event-conversion-utils.ts
store/modules/events.ts

This PR restores `Online` as a `Location` although it copies it to an event type for the UI to be able of filtering those by type as agreed in offline conversations.
It depends on #527 and #526 to be solved before removing temporal code.

Add temporal fallbacks while waiting for produt final decisions

---

components/experiments/ExperimentHeader.vue
components/ui/Cta.vue
pages/index.vue

Fix #479
This PR makes using the CTA as the component the website uses for converting users. So, it is used consistently across all the site. The chosen style corresponds to that of the community site:
Other uses of links showing like buttons have been converted into simple links like the "Explore the code button" in the experiments individual pages.

Leave only one CTA and convert event link to the source code into actual links

---

constants/menuLinks.ts

Fix #599 
The previous location no longer exists. This is the new "most basic" tutorial available.

Point Turorials link to qiskit.org again

---

components/layouts/PageFooter/index.vue

The `contained` mixing modifies the left and right paddings of the element which is applied to. This violates the principle of minimum astonishment (tracked on #657) which I think lead to some unnecessary extra margins.

Fix alignment of the footer

---

components/landing/LearnCard.vue

Fix #668
Contrary to the Figma design, this PR does not use a different image for mobile but tries to leverage the same one with small position corrections.

Add responsive capabilities to the Learn with Qiskit section

---

constants/menuLinks.ts

The IBM url shortener works on TLS too.

httpS for ibm.co/joinqiskitslack on the footer

---

.travis.yml
deploy/deploy_cos.sh

This commit fixes the potential issue where a failed website build
results in rclone deleting the contents of the bucket. This is
accomplished by making 2 changes. The first is to set errexit in the
deploy_cos.sh bash script, which results in any intermediate failure in
the script exiting instead of continue with the execution of the script.
The second is to make the travis script rely on && instead of multiple
script lines. Travis doesn't exit when an earlier script line fails and
instead continues like bash without errexit and fails after all lines
are executed. To work around this all the deploy commands are run in a
single line using && so that it will exit after the website build fails.

Set errexit and use && for travis deploy

---

pages/advocates/index.vue

Replaces the `apply now` link on the advocates page with `closed`

---

components/landing/LandingCta.vue
components/landing/TheFeatures/index.vue
components/landing/TheHeroMoment/index.vue

Fix #855 
In addition, this PR:
- Refactors LandingCta
- Aligns landing cta elements to fit Figma design on small and medium devices
- Unifies primary and secondary landing cta to fit Figma design

Add link to overview in home page

---

pages/events/index.vue

Resolves #934 
**Description**
With the updated designs for the Community Events page, this work will include updating the entire page to use the same light theme as the Learn page (for example).
**Changes proposed**
- update styles to use light theme colors
- override styles on child components 
**Note**
Because this page's styling is `scoped`, I used the [deep selector approach](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors), mentioned in the Vue-Loader docs. This feels weird from a specificity _and_ syntax standpoint, and I'd love to hear recommendations for a better way to approach this.

Convert Events page to light theme

---

pages/events/index.vue

Resolves #955
Updated the colors on the dropdown tabs for mobile.
Note: in order to not recreate another v-deep selector, I had to remove the scoped attribute in the component's style tag, which I think should be fine since this is an event-page.

Fix mobile filters to light theme

---

components/advocates/MeetTheAdvocates.vue
components/ui/AppCheckbox.vue
components/ui/AppFiltersResultsLayout.vue
components/ui/AppMultiSelect.vue
pages/advocates/index.vue
pages/events/index.vue
store/modules/events.ts

Fix #1074 
This PR:
- Creates a component for the filters-results layouts we have on learn's, events', and advocates' page but it's only used on the advocates' page. We have an [issue to extend this layout](https://github.com/Qiskit/qiskit.org/issues/944) to the rest of the pages
- Creates an AppCheckbox component that should be finished and reused on the events' page when [implementing the behavior of the filter](https://github.com/Qiskit/qiskit.org/issues/1086)
I did my best naming the components, but I'm not sure if it's easy to follow, so please, if you have suggestions, let me know

Implements meet advocates layout

---

components/landing/TheQuickStart/StartLocally.vue

Fixes #1046 
Changed the components/landing/TheQuickStart/StartLocally.vue file to reflect the correct version of Python required for qiskit.

Changed the content on landing page about python dependency

---

.github/workflows/deploy.workflow.yml

Fix #872 
Environment variables in GitHub actions seem to be set per each individual run, not globally. The environment variable needed for fetching the correct events should be set during generation.

Add AIRTABLE_API_KEY env variable where needed

---

components/landing/TheHeroMoment/index.vue

Fix #1226 
The component uses Vue router navigation by default. However, some
URLs are not part of the Nuxt project and cannot be navigated using
the default Nuxt mechanism. One of them is `/documentation`
Passing the complete URL, we are forcing the component to use
native navigation when jumping to this URL.

Provide the absolute URL to for browser navigation.

---

components/ui/AppCard.stories.ts
components/ui/AppCard.vue

**Note:** This is only one part of https://github.com/Qiskit/qiskit.org/issues/884#issuecomment-733034345
---
Make the necessary adjustments to the **AppCard** Storybook story to showcase the various Storybook functionalities.
Only the card's image is currently not showing due to _lazy-background_ not loading the image. I tried to dig deeper into this but couldn't make it work. But I personally believe that this should not be an impediment for the scope of this PR.
---
Closes #1155

Create Storybook showcase story

---

components/learn/TheLearningResourceList.vue

This PR changes the display property of a wrapper element to avoid an undesired overflow that resulted in a black background being shown on mobile devices.
Here is a JSFiddle showing the basic concept of this change: https://jsfiddle.net/fsby7krt/
---
Closes #1194

fix: remove undesired overflow in mobile

---

plugins/segment-analytics.ts

This PR adds a missing type to a Promise in order to support [`@nuxt/typescript-build`'s upgrade to version 2.0.4](https://github.com/Qiskit/qiskit.org/pull/1318), which uses TypeScript 4.1.
Related to #1318

chore: type Promise return to support TS 4.1

---

plugins/segment-analytics.ts

This PR rejects a Promise on error properly, in order to support [@nuxt/typescript-build's upgrade to version 2.0.4](https://github.com/Qiskit/qiskit.org/pull/1318), which uses TypeScript 4.1.
---
Related to #1318

fix: reject Promise on error to solve TS issue

---

components/events/seminar-series/UpcomingSeminarSeriesSection.vue
content/events/next-seminar-series-event.json
content/events/past-community-events.json
content/events/past-seminar-series-events.json
content/events/upcoming-community-events.json
content/events/upcoming-seminar-series-events.json
hooks/event-conversion-utils.ts
hooks/update-events.ts

With this PR, the Seminar Series events will be fetched from Airtable.
3 files will be generated:
- `next-seminar-series-event.json`
- `upcoming-seminar-series-events.json`
- `past-seminar-series-events.json`
This PR only includes displaying the data of the upcoming events in the page's table, since the past events (#1328) and next event (#1327) will be handled later, once those components are integrated into the feature branch.
---
Closes #1312

feat: fetch Seminar Series events from Airtable

---

components/events/seminar-series/PastSeminarSeriesSection.vue
components/events/seminar-series/UpcomingSeminarSeriesSection.vue
constants/appLinks.ts
pages/events/seminar-series.vue

This PR displays the past Seminar Series events in the Seminar Series event page, with data fetched from Airtable.
It also makes some copy changes to the tables, based on the [latest version of the Figma design](https://www.figma.com/file/nqFBhDOUq6Dknbw9pM92AE/1263-individual-event-pages?node-id=331%3A1931).
To test is on Vercel, go to the route `/events/seminar-series`.
For some reason, this PR shows changes in 13 files in GitHub, but when using the [_compare_ function](https://github.com/Qiskit/qiskit.org/compare/feature/seminar-series-new-layout...eddybrando:ev-issue-1300-past-seminar-series-events-table), changes in 4 files are shown.
This PR actually just changes files in those 4 files. The rest are already in the target branch.
---
Closes #1300

feat: display past Seminar Series events table

---

components/ui/AppMosaic.vue

This PR prevents an image overflow in the second section of the mosaic.

fix: mosaic image overflow

---

pages/events/seminar-series.vue

This PR adds 2 missing links for the **Helpful Resources** section of the Seminar Series page.
It also includes a minor copy fix in the **Stay informed** block.

fix: missing helpful resources links

---

components/layouts/TheMenu/MobileMenu.vue
package-lock.json

This update didn't make the final push, as a part of #1183, but fixes the breakpoint for when the mobile-menu footer should appear.
Adding screen capture to show fix in place:
https://user-images.githubusercontent.com/6276074/106607418-85052d80-6520-11eb-9401-6a6884934ebd.mov

Fix mobile-menu footer breakpoint

---

components/events/seminar-series/PastSeminarSeriesSection.vue
components/events/seminar-series/SeminarSeriesDataTable.vue
components/events/seminar-series/SeminarSeriesHeader.vue
components/events/seminar-series/UpcomingSeminarSeriesSection.vue
content/events/next-seminar-series-event.json
hooks/update-events.ts
pages/events/seminar-series.vue

With this PR, the **next Seminar Series event** will be extracted from the list of **upcoming events** on the **Header** component directly, instead of being stored once as a JSON file with a hook event.

refactor: next event from events json

---

.github/workflows/deploy.workflow.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Fix #828 
This PR is a follow-up to the action of renaming `master` to `main` on GitHub. It replaces the apparitions of `master` in the codebase. We need to review the wiki pages too.
Vercel should not be affected and the GitHub workflows have been updated accordingly, although I would appreciate a review here @vabarbosa since you set them up.

Replace master with main in the codebase

---

constants/menuLinks.ts
mixins/menu.ts

This PR adds a link in the navbar that points to the demo Textbook page.
This is only needed during development for testing purposes.
**Note:** There is a small design bug in the _big screen_ view (the margin between "Learn" and "Textbook" is small, and the margin between "Textbook" and "Community" is big) due to a CSS rule targeting a _nth:child_. But for the purpose of this issue (just having the link to test the page easily), it can be ignored.
---
Closes https://github.com/Qiskit/qiskit.org/issues/1443

feat: add link to "Textbook demo"

---

pages/textbook-demo/index.vue

This PR creates an empty page with the Qiskit layout (including the navbar and footer) for the new **Textbook Demo**.
---
Closes #1445

feat: create "Textbook Demo" page

---

pages/textbook-demo/index.vue

This PR creates the "Helpful Resources" section for the new Textbook landing page.
**Note:** This section currently contains placeholder content. When the final content is ready, it will be updated in #1448. The same goes for the "segments" for link events tracking.
**Note 2:** Please wait until #1446 is merged before merging this PR.
---
Closes #1447

feat: create "Helpful Resources" section for Textbook LP

---

components/metal/IntroSection.vue

Fixes #1407
The PR updates the CTA text of the Metal page to reflect the changes in the formulary. I can confirm the link remains the same.

Update text in the CTA of the metal website

---

components/ui/BasicLink.vue

Check if the `url` exists before using it to avoid problems when the `url` is not present

Improves basic link

---

components/textbook-demo/ExternalRecommendedReadings.vue
components/textbook-demo/LearningPathExternalRecommendedReadings.vue
pages/textbook-demo/learning-paths/introduction-course.vue

This PR creates the **External Recommended Readings** section for the new Learning Path landing page.
**Note:** Please first check #1514 and merge it into the feature branch. Then rebase this PR before merging.
---
Closes #1502

feat: create "External Recommended Readings" section

---

components/ui/BasicLink.vue

Propagate emission of the _mouseenter_ event to allow for more mouse interactions while still leveraging the tracking functionalities of this component.

feat: emit "mouseenter" event

---

components/ui/AppMegaDropdownMenu.vue

This PR adds the functionality to close the mega dropdown when the user clicks outside of it.
You can test it here: https://qiskitorg-git-fork-eddybrando-ev-issue-1526-mega-me-8c5146.vercel.app/textbook-demo
---
Closes #1526

feat: close dropdown when clicking outside

---

.github/CODEOWNERS

I still watch the repository (so I get GitHub notifications from each PR).
But since I'm not working daily on qiskit.org, I avoid receiving emails from each PR.

Remove @abdonrd as code owner

---

components/ui/AppIntroductoryContent.vue
pages/overview.vue
pages/textbook-demo/index.vue

This PR creates two layouts for the `AppIntroductoryContent` component, which adapts depending on its context:
- **Full width** (default) now aligns with the general layout by reserving 1/4 of the horizontal space for the description text and 3/4 for the slot content
- **Narrow** (by passing the `narrow` prop), which is the layout currently being used in https://qiskit.org/overview/
---
Closes #1551

feat: align `AppIntroductoryContent`'s layout

---

components/overview/ContentAccordion.vue

Right now the accordion component has min-size set to 30.5rem. The consequence is that when we have small content, we can see a bigger space between the link and the bottom of the accordion element:
This PR removes that min-size, so the accordion size change following the content size:

Removes min size for accordion content

---

components/ui/AppDataTable.vue

Small style update to address table header spacing.
Fixes this bug: 👇

Fix table header spacing

---

new-content/events/summer-school-2021.yaml

We are only using the front-matter data of the markdown that is written in yaml.
To make the edition easier using GitHub editor and prevent mistakes, now the `.md` is `.yaml`. GitHub editor shows syntax coloring correctly.
Before:
After:

Markdown changed to yaml

---

components/ui/AppPageHeaderWithCard.vue
pages/events/physics-of-computation.vue
pages/events/seminar-series.vue

With the recent changes on the Summer School page, we need to be more flexible with the header description to allow having links. With this PRs we will be able to do it by passing the description through slots

Modifies AppPageHeaderWithCard to pass description through slots

---

components/advocates/MeetTheAdvocates.vue
components/learn/TheLearningResourceList.vue
components/ui/AppFiltersResultsLayout.vue
pages/events/index.vue
pages/learn/index.vue

Fixes #944 
On this PR, the Learn, Advocates and Events pages share the same component for creating the layout of the aside filters and the results container

Reuse filters and results layout

---

components/textbook-demo/LearningPathPagesSection.vue
components/textbook-demo/PrerequisiteMaterialSection.vue
components/ui/AppDescriptionCard.vue

Fix #1879
To see the changes go to `/textbook-demo/learning-paths/introduction-course`
Note: Although is no needed right now, I didn't remove the ProgressCircle component. We should check if we need it on platypus first

Deletes unnecessary tracking elements

---

components/textbook-demo/TextbookDemoContentMenuSection.vue
components/ui/AppMegaDropdownMenu.vue
pages/textbook-demo/learning-paths/introduction-course.vue

This PR adds the "learning content mega dropdown" to the **learn path** page.
The width of the dropdown field is now no longer fixed but rather uses the Carbon columns as defined in Figma.
---
Closes #1864

feat: add mega menu dropdown to "learn path" page

---

components/textbook-demo/TextbookDemoHeader.vue

This PR implements the logic to display and hide a _fixed to the top_ version of the **mega menu dropdown** when the _regular_ **mega menu dropdown** toggles its visible state.
The _fixed to the top_ **mega menu dropdown**'s transition is animated with two effects:
1. It moves vertically when appearing / disappearing
2. It fades out when disappearing to avoid a too harsh of an effect when the dropdown is opened whilst scrolling to the top
**Note:** To test it, go to the URL `/textbook-demo` in the Vercel preview.
---
Closes #1855

feat(textbook): display fixed mega menu on scroll

---

components/textbook-demo/TextbookDemoContentMenuSection.vue
components/textbook-demo/TextbookDemoHeader.vue
components/ui/AppMegaDropdownMenu.vue
plugins/segment-analytics.ts
tests/plugins/segment-analytics.spec.ts

This PR implements the Segment analytics tracking for search terms in the **Textbook Mega Menu**.
The search terms are being tracked via the `trackEvent` function of Segment, similarly to the "Clicked CTA" events.
We're sending some additional event information to Segment with this event:
1. **Location:** The name of the component (for example: `Textbook mega menu`)
2. **Text:** The searched term (for example: `algorithm`)
The tracking event is triggered 750 milliseconds after the user stops typing something in the **Textbook Mega Menu** component.
---
Related to: #1847, #1857
Closes: #1859

Ev issue 1859 track mega menu search terms

---

components/advocates/AdvocatesJoinSection.vue

This PR adds click events tracking to the "Join the program" CTA in the advocates page.
The `action` is in our current structure (`<page> > <section> > <cta-label>`). There is an ongoing conversation about restructuring this in https://github.com/Qiskit/qiskit.org/issues/1511#issuecomment-862284188, but until a conclusion is reached, we should keep using the current approach for consistency.
---
Closes #1883

feat(advocates): track clicks on "Join the program" CTA

---

components/textbook-demo/TextbookDemoContentMenuSection.vue
components/textbook-demo/TextbookDemoHeader.vue
components/ui/AppMegaDropdownMenu.vue
pages/textbook-demo/course/introduction-course.vue

This PR makes the Textbook Mega Menu component stick to the top when scrolling down in the courses pages.
To test it, go to a course page in the Vercel preview, like `/textbook-demo/course/introduction-course`.
https://user-images.githubusercontent.com/22047320/122562829-c74c8880-d043-11eb-9010-9271984fc1da.mov
---
Closes #1891

feat(textbook): sticky mega menu

---

ARCHITECTURE.md
README.md

Expand technical architecture overview section in the **README.md** file as suggested in #1030.
The newly created **ARCHITECTURE.md** aims to serve as a simple but coherent and complete overview of how the website is architected, without going into too much detail.
It should be seen as a general guide of our current practices and a good onboarding document for project newcomers.
Some updates have been also made to the **README.md** file to reflect the current directory structure and fix minor typos.
---
Closes #1030
Replaces #1225

feat: add technical architecture overview

---

deploy/deploy_cos.sh

The Qiskit schemas have been moved: https://github.com/Qiskit/qiskit-terra/pull/6558
Fix #2011

Get the Qiskit schemas from the new repository

---

pages/events/india-week-of-women-in-quantum.vue

Update requested by the India's team:
On the https://qiskit.org/events/india-week-of-women-in-quantum/ page, update
Day 2 Event Schedule for Speaker Kavitha Yogaraj’s Affiliation:
IBM Research, India   →   IBM GBS India

Updates affiliation on the india week of women in quantum page

---

components/textbook-beta/CoursePagesSection.vue
pages/textbook-beta/summer-school/quantum-computing-and-quantum-learning-2021.vue

Fixes the first and third issues from [this comment](https://github.com/Qiskit/qiskit.org/pull/2190#issuecomment-928981633)
- Link pointing to Linear Algebra 
- Sticky preview frame for the Course pages

Update link and sticky preview frame

---

.github/workflows/preview.yml
CONTRIBUTING.md

Related with #2276 and https://github.com/qiskit-community/platypus/pull/199
The idea with this PR is to disable the preview-ga for forks and drafts to prevent false errors in the PR.

Disable preview for forks and drafts

---

constants/megaMenuLinks.ts

an [update/re-alignment of the labs](https://github.com/qiskit-community/platypus/pull/186) resulted in the URLs changing thus breaking the links in the megamenu.
this PR updates the lab links in the megamenu drop down
related: https://github.com/Qiskit/qiskit.org/issues/2332 , https://github.com/qiskit-community/platypus/pull/217
---
fyi, in an [upcoming update](https://github.com/qiskit-community/platypus/pull/174) there will be a [new endpoint which returns the list of courses](https://github.com/qiskit-community/platypus/blob/bcdfc0c80fe1d8afba426f74bc8440836beac2bd/server/app.ts#L80-L90). we can perhaps update the megamenu in the future to make use of the endpoint to obtains  the links. this way it needs not be manually updated if the urls/courses changes

update megamenu lab links

---

Dockerfile

Fix https://github.com/Qiskit/qiskit.org/issues/2395
this PR updates the build script in the Dockerfile to use Nuxt generate (`npm run generate`) instead of just Nuxt build (`npm run build`)
Nuxt build does not create the `/dist` directory needed for deploying of static target

Run `generate` instead of `build`

---

Dockerfile

In this PR we are adding the `package-lock` and the `npm ci` to the Dockerfile to avoid versions problems between libraries updates.
Fix #2399

Fix docker installation dependencies

---

.github/CODEOWNERS

I don't need to be strictly a reviewer for all PRs.
There are many PRs that I have no knowledge or context of.
And so I reduce the level of email notifications.
I still watching the repo, so I see the activity in the [GitHub notifications](https://github.com/notifications).

Remove abdonrd as code owner

---

.github/workflows/preview.yml

This PR tries to reuse the new github action that builds and push a docker image to IBM container registry. We are externalising it to improve the reusable logic between projects and interoperability.
Fix #2398 
Related with #2395

Reuse github action preview

---

components/landing/TheQiskitCapabilitiesSection/CodeCell.vue
components/landing/TheQiskitCapabilitiesSection/index.vue

Resolves #2419 
This PR **temporarily** removes the scroll-based highlighting.
We'll reintroduce this styling once #2411 is complete.
Branch preview here - https://qiskit-org-pr-2420.dcq4xc5i083.us-south.codeengine.appdomain.cloud/

Remove scroll-based code cell highlighting

---

.github/workflows/deploy.yml

Seems like double quotes doesn't work on the `if` condition:
https://github.com/Qiskit/qiskit.org/actions/runs/1708639108

Fix deploy.yml quotes

---

.github/workflows/preview-cleanup.yml
.github/workflows/preview-deploy.yml

related to https://github.com/Qiskit/gh-actions/issues/16
this PR updates the workflow and action naming to be more appropriate and distinguishable.
currently both the creating and the destroying preview workflow have the same name `Preview` which can cause confusion when reviewing the workflows in the **Actions** tab
related https://github.com/Qiskit/platypus/pull/344

update workflow naming

---

components/logic/CourseOverviewPage.vue

Fix https://github.com/Qiskit/qiskit.org/issues/2567
`/textbook-beta/course/machine-learning-course`
`/textbook-beta/summer-school/quantum-computing-and-quantum-learning-2021`

Course Overview pages — preview image overlapping footer

---

components/textbook-beta/StartLearningSection.vue
components/ui/AppCard.vue

Per offline conversations with @techtolentino, this description doesn't look so good.
This PR adds an additional configuration for the `AppCard`.
`/textbook-beta/`

Fix description content on cards

---

constants/megaMenuLinks.ts

Fixes https://github.com/Qiskit/qiskit.org/issues/2595
Updated links to pages that exist
I'm not sure how much of these links will need to be updated, once this PR merges https://github.com/Qiskit/platypus/pull/967. I just wanted to get the fix in, in case users come to the site and use the menu, between major merges. In other words, I didn't wanna leave broken links on the site for the sake of UX.

Fix broken links in MegaMenu

---

layouts/default-max.vue
pages/index.vue

Fixes https://github.com/Qiskit/qiskit.org/issues/2592
add a banner announcing qiskit runtime to the home page
preview: https://qiskit-org-pr-2594.dcq4xc5i083.us-south.codeengine.appdomain.cloud/
add QiskitBanner to `index.vue` page with runtime announcement message.
banner style is updated to match design https://www.figma.com/file/hvicTzjohhLyBRbUzmCsfV/2592-home-page-banner
- review design and compare to banner in [preview build](https://qiskit-org-pr-2594.dcq4xc5i083.us-south.codeengine.appdomain.cloud/)
- review updates to `pages/index.vue`
---
CC @JRussellHuffman @lerongil

add runtime banner

---

components/textbook-beta/StartLearningSection.vue

Fixes #2598 
- add new "Chapters" section to the `StartLearningSection` 
- organize chapters into the appropriate Chapters section
https://qiskit-org-pr-2601.dcq4xc5i083.us-south.codeengine.appdomain.cloud/textbook-beta

Add Chapters section to learn page

---

constants/summerSchool2022Content.ts

Fixes https://github.com/Qiskit/qiskit.org/issues/2628
Adds Summer School 2022 registration link
Following the [conversation happening in our internal Community Slack channel](https://ibm-quantumcomputing.slack.com/archives/GMU4N7RM0/p1653580820269489), and after syncing with @justjosie, it was decided that our Summer School page needed to be updated.
- visit `/events/summer-school`
- review UI and test link
https://user-images.githubusercontent.com/6276074/170530232-e83099b3-a8cd-488c-985b-47397448c060.mov

Add Summer School registration link

---

components/landing/TheQiskitCapabilitiesSection/CodeCell.vue

Fixes #2617 
- made updates to the homepage "What Can Qiskit Do" section
- removed the _numbered_ comments that seemed to be out of order, and not have meaning
- split long comment into multiline
- review the updated comments
- review UI at different breakpoints
**Note:** the first obvious solution was to use some sort of overflow + scrolling solution, however, I opted for this pattern so that the code is _always_ within view, and the user wouldn't have to scroll to see the rest of _any_ code. (In addition, going the overflow + scroll route required more code changes that needed)
https://qiskit-org-pr-2626.dcq4xc5i083.us-south.codeengine.appdomain.cloud/
https://user-images.githubusercontent.com/6276074/170507108-825af9af-c495-4a17-b731-6896c246f546.mov

Restructure homepage code cell comments

---

components/ecosystem/TestTable.vue

Added accessible labels to test status icons on ecosystem page.
Closes  #2653
Since the icons are inline `<svg>` elements, they do not support adding an `alt` property. So, since there is no visible text to describe the icons, I opted to implement the accessible labels with `aria-label` as [recommended by MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role#associated_wai-aria_roles_states_and_properties).

Add accessible labels to test icons on ecosystem page

---

store/ecosystem.ts
tests/store/ecosystem.spec.ts

Due to an update to the ecosystem repo yesterday the filters functionality on the qiskit.org page broke. This PR fixes the issue (caused by changing between upper and lowercase).
This PR also arranges the order of the tier filters so that "Main" is always at the top of the list (and the rest is in the order they appear in `members.json`
@1ucian0 @IceKhan13

Bug: Fixed filters bug and put "Main" at top of filters list

---

pages/ecosystem/index.vue

This PR fixes a bug where the test type field in the test table was being formatted in the frontend which caused issues when things in the backend repo were updated. Now the backend handles the string formatting so we can remove the formatting on this side and the test table can just update dynamically.
The bug fix is only removing 2 lines (133 and 134 in `ecosystem/index.js` but there are also some linting fixes.
before (with bug)
after (without bug)

Ecosystem: fix test table bug

---

pages/ecosystem/index.vue
plugins/carbon.ts

This PR adds github star data for each project to the cards. We didn't discuss a specific design for the star info so I just went with this simple version. Not sure if just the star icon is clear enough or if there should be some extra text as well? I've seen similar ecosystem pages use the github logo but I personally don't think that is any clearer. Would appreciate any thoughts, particularly from @JRussellHuffman 😄

Ecosystem: Add github star data to project cards

---

.github/ISSUE_TEMPLATE/user_research.yml
.github/ISSUE_TEMPLATE/user_story.yml

This is a follow-up of https://github.com/Qiskit/platypus/pull/1353.
> Extended our issue templates to include items from the Sprint Retro:
> 
> - Future of Feature (to `user_story.yml`)
> - User Research Template (`user_research.yml`)

docs: update issue templates

---

pages/learn/intro-qc-qh.vue
pages/textbook-beta/index.vue
pages/textbook-beta/summer-school/quantum-computing-and-quantum-learning-2021.vue

Fixes #2717 
- using same redirect strategy that we've used for previous, deprecated pages
- visit localhost:3000/learn/intro-qc-qh
- visit localhost:3000/textbook-beta/summer-school/quantum-computing-and-quantum-learning-2021

Add redirects for broken pages

---

components/ui/AppCard.vue

fixes #2759 
This bug is caused by a css item that was previously moved into the scoped section but actually should have stayed in the global section. This caused that css to be ignored for some reason so this PR just moves it to the correct place so it is actually implemented.
now the text is not cut off by the side of the screen anymore:
cc: @1ucian0

Ecosystem: Fix tooltip bug

---

hooks/event-conversion-utils.ts
tests/hooks/event-conversion-utils.spec.ts

Closes #2746
Quantum explorers event not showing on events page.
Ongoing events weren't showing on events page, because the code didn't contemplate its case.
A boolean constant was created to identify this events, under the condition of having started but not yet finished, which suffice the characteristics of ongoing events. 
This events will be included in the future events tab from now on.

fix(events): add ongoing events in "future events"

---

components/events/fall-fest/UniversityDirectorySection.vue
constants/fallFest2022Content.ts

Closes #2822 
[View branch updates here](https://qiskit-org-pr-2823.dcq4xc5i083.us-south.codeengine.appdomain.cloud/events/fall-fest)
https://user-images.githubusercontent.com/6276074/193866472-653c0491-3019-4714-99c6-6d8d69b897d2.mov

update event links and content

---

pages/ecosystem/index.vue

Noticed this warning while building:
```
: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($spacing-01, 2) or calc($spacing-01 / 2)
More info and automated migrator: https://sass-lang.com/d/slash-div
╷
287 │     margin-top: $spacing-01 / 2;
│                 ^^^^^^^^^^^^^^^
╵
pages/ecosystem/index.vue 287:17  root stylesheet
: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($spacing-01, 2) or calc($spacing-01 / 2)
More info and automated migrator: https://sass-lang.com/d/slash-div
╷
295 │       margin-top: $spacing-01 / 2;
│                   ^^^^^^^^^^^^^^^
╵
pages/ecosystem/index.vue 295:19  root stylesheet
```
This PR wraps divisions in `calc` to …

Wrap division in 'calc' to suppress warnings

---

constants/summerSchool2022Content.ts
pages/events/summer-school.vue

this PR removes the registration for summer school 2022 from it's event page
[preview link](https://qiskit-org-pr-2849.dcq4xc5i083.us-south.codeengine.appdomain.cloud/events/summer-school/)
Closes https://github.com/Qiskit/qiskit.org/issues/2848
- removed the eventbrite registration links
- removed the registration CTA
- replaced early registration text with `See you next year!`
1. review updates made to the summer school page
2. go to the [summer school event page](https://qiskit-org-pr-2849.dcq4xc5i083.us-south.codeengine.appdomain.cloud/events/summer-school/)
3. review the event page shows the updates (i.e., doesn't show registration)
**before**
**after**

remove registration

---

components/learn/StartLearningSection.vue
components/ui/AppCard.vue

For the new 'basics of quantum information' course, we need a way to separate the title of the specific course from it's wider series. This PR adds the ability to add a subtitle to a card for this specific purpose.
I've added an extra HTML tag & some css to `AppCard.vue`, and you can now send an optional `subtitle` value to the card. From my tests, these changes don't seem to affect the appearance of the other cards. Hope I've done this right!
No cards currently use this except the new basics of quantum information course which isn't merged yet, so you'll need to add a `subtitle` field to an existing card to try this out (see [3f5efc0](https://github.com/Qiskit/qiskit.org/pull/2831/commits/3f5efc04b2339a315410e45a0401c18a985239c0) for an example).

Add card subtitle feature

---

layouts/default-max.vue
layouts/default.vue
pages/index.vue

Fixes https://github.com/Qiskit/qiskit.org/issues/2898
- Removed `QiskitBanner` import, component, and styles
- Updated `default` and `default-max` layouts w/ a small CSS fix because the `qiskit-ui-shell` component + the hero background grid, was causing a _double line_ effect
**BEFORE CSS update**
**AFTER CSS update**

Remove Qiskit Runtime banner

---

components/landing/TheLearnSection/LearnCard.vue
components/ui/BasicLink.vue

Fixes #2847 
- updated "Get learning" link to use relative path
- added check for `isInternal` links, which are `url`'s that begin with a `/`
- added `isInternal` links to the `isAnchor` check which will render a valid `href` 
- also fixes the "Go to this course" links for the `AppCard`s on the `/learn` page
https://qiskit-org-pr-2911.dcq4xc5i083.us-south.codeengine.appdomain.cloud/
- user can now tab to the "Get learning" link
- user can `cmd + click` to open link in a new tab
https://user-images.githubusercontent.com/6276074/211906227-3cc75713-c2ab-4837-87d3-29c0468c479a.mov

Fix accessibility for internal links

---

components/landing/TheQiskitCapabilitiesSection/index.vue

Fixes #2846 
- updated the `copyToClipboard` function to use `innerText` instead of `textContent`
- handled TS error using conditional (borrowed approach from [this source](https://bobbyhadz.com/blog/typescript-property-innertext-not-exist-type-element#:~:text=The%20reason%20we%20got%20the%20error%20is%20that%20the%20return%20type%20of%20the%20document.querySelector%20method%20is%20Element%20%7C%20null%20and%20the%20innerText%20property%20doesn%27t%20exist%20in%20the%20Element%20type.))
https://qiskit-org-pr-2910.dcq4xc5i083.us-south.codeengine.appdomain.cloud/
https://user-images.githubusercontent.com/6276074/211881711-efa41204-13d8-4548-b43f-1a5907fff545.mov

Update copy code formatting

---

store/advocates.ts
tests/hooks/advocate-conversion-utils.spec.ts
tests/store/advocates.spec.ts

Fix https://github.com/Qiskit/qiskit.org/issues/2736
On the advocates page:
- `North America` is now `America (North)
- `South America` is now `America (South)
- Locations now are on alphabetical order
- Go to the [advocates page](https://qiskit.org/advocates/) 
- Check that the locations are in alphabetical order
- Check that the label on the advocate card also replace North/South America with America (North/South)
- Check that everything still works as expected

feat(advocates): order and rename locations

---

.gitignore

This PR adds the pictures downloaded from airtable with `npm run generate` to .gitignore

feat: adds photos downloaded from airtable to .gitignore

---

package-lock.json
package.json

The [`ui-shell` component has changed](https://github.com/Qiskit/web-components/issues/193), so we need to update the `@qiskit/web-components` package to the last version (`0.11.1`)
Check the top menu > Documentation
Instead of having: **_Getting started > Overview_**, we should have:
- **_Start Here > Documentation Home_**
- **_Start Here > Getting Started_**

Updates @qiskit/web-components to the last version

---

pages/events/index.vue
store/events.ts

Closes #2924 
This PR adds a new tab to the [qiskit.org/events](https://qiskit.org/events/) page, where users can view the Airtable calendar, and get advantage of the integrated features.
Styling as much as I'd have liked to has not been possible because the iframe that's been added it's just a view of the original calendar. Either way, an outline was added as well as some margins.
Here's how it looks both on big size screens and smaller ones.

Calendar added via Iframe (airtable)

---

components/providers/AccordionLayout.vue
components/providers/ContentAccordion.vue
constants/providersContent.ts
pages/providers.vue

Closes #2991 
https://qiskit-org-pr-3041.dcq4xc5i083.us-south.codeengine.appdomain.cloud/
- Adds AppCta to the Provider page sidebar (same approach as the Overview page)
- Adds a bottom section on the Provider page (like Ecosystem hero, but at the bottom)
- Removes images from Accordion layout (request from @JRussellHuffman)
- please review CTA implementation
- please also review the CTA labels, the bottom section title, and the copy since I made this up as a first attempt
https://user-images.githubusercontent.com/6276074/226672391-12a53516-d773-4d3e-b479-552177d6ae84.mov

[Providers] add CTAs linking to provider documentation

---

components/landing/TheQuickStart/Algorithms.vue
components/landing/TheQuickStart/ProvidersList.vue
components/landing/TheQuickStart/index.vue

Closes https://github.com/Qiskit/qiskit.org/issues/3052
- restructured the Quick Start widget's use of the Carbon grid
- updated styles
- removed "Test some algorithms" label
- now, the widget components (ProvidersList + Algorithms) are visually aligned at the top
https://user-images.githubusercontent.com/6276074/227566741-f9bb719d-7ab0-4baa-9ef5-28a17b634f9e.mov

[Providers] update providers layout

---

pages/events/index.vue

Added segment to the tabs that split the events list in the events page, resolving #3004.
For some reason, I wasn't able to double check everything because the Segment extension wasn't working for me.
Also, I added some logic to skip first loading of the page so that segment doesn't register the default selected tab as if the user had clicked on that one.

Segment Tracking added to event tabs

---

pages/overview.vue

Fixes #3090 
- handled redirection based on our previous approach with the [qiskit/textbook-beta file](https://github.com/Qiskit/qiskit.org/blob/main/pages/textbook-beta/index.vue)
- please let me know if the approach is okay to use here, or if we need a different approach
In the preview branch, try navigating to the `/overview page` and you'll find that you're redirected to the homepage.
https://qiskit-org-pr-3091.dcq4xc5i083.us-south.codeengine.appdomain.cloud/overview

feat(providers): add deprecated overview page redirect

---

components/learn/LearnHeader.vue

this PR is part of a bigger set of changes required as the Qiskit textbook get re-organized/versioned: https://github.com/Qiskit/platypus/issues/2046
Remove `(beta)` from heading
the header text is updates and the beta label was removed
- review updated file
- review page in preview link
**before**
**after**

remove beta from label

---

components/Learn/LearnPageHeader.vue
pages/learn/index.vue

As the textbook is graduating out of beta, probably the title and banner needs to be updated. 
before
after

Remove (beta) and banner from textbook-beta page

---

package-lock.json
package.json

This PR updates Nuxt to v3.4.1: https://github.com/nuxt/nuxt/releases/tag/v3.4.1
They now include a fix that solves our issue with v3.4.0: https://github.com/Qiskit/qiskit.org/pull/3115#issuecomment-1505447300
This PR should also close https://github.com/Qiskit/qiskit.org/pull/3115 automatically the next time Dependabot checks our dependencies.

chore(deps-dev): bump nuxt from 3.3.2 to 3.4.1

---

components/Advocates/AdvocatesMeetTheAdvocates.vue
components/Ecosystem/EcosystemTestTable.vue
components/Events/Calendars/EventsCalendarsAppleInstructions.vue
components/Events/Calendars/EventsCalendarsGoogleInstructions.vue
components/Events/Calendars/EventsCalendarsOutlookInstructions.vue
components/Events/EventsSummerSchoolFaq.vue
components/Landing/LandingQuickStart/LandingQuickStartProvidersCodeExamples.vue
components/Landing/LandingQuickStart/LandingQuickStartStartLocally.vue
components/Landing/QiskitCapabilitiesSection/LandingQiskitCapabilitiesSectionComponent.vue
components/Learn/LearnContentMenuSection.vue
components/Learn/LearnStartLearningSection.vue
components/Ui/UiCard.vue
components/Ui/UiCodeSnippet.vue
components/Ui/UiDataTable.vue
components/Ui/UiMultiSelect.vue
components/Ui/UiSyntaxHighlight.vue
components/providers/ProvidersContentAccordion.vue
layouts/default-max.vue
layouts/default.vue
nuxt.config.ts
pages/ecosystem.vue
pages/events/fall-fest.vue
pages/events/index.vue
pages/events/summer-school.vue
plugins/components.client.ts

Fixes web component imports
In order to see the providers content, we need ssr. To enable ssr, we need some modifications when importing the web components
Open the web and check that the providers content is shown

Enables SSR and fix web components import

---

components/Learn/LearnContentMenuSection.vue
components/Learn/LearnPageHeader.vue

This PR fixes an issue introduced in https://github.com/Qiskit/qiskit.org/commit/ea4b340bbb4c52e4275a46cc14a4c1038f175fbf that resulted in the Qiskit Mega Menu web component not showing its content. This is solved by only rendering the web component on the client using the [<ClientOnly> component](https://nuxt.com/docs/api/components/client-only).

fix(learn): only render mega menu on client

---

hooks/update-events.ts

Widens the range of time to determine which upcoming events to display up to two months (62 days).
Solves #3202

Show upcoming events 2 months in advance

---

components/Ecosystem/EcosystemTestTable.vue

[EcosystemTestTable]: Tooltip is using the wrong color
Changed the EcosystemTestTable toolTip content background-color to dark
closes #3208 
https://github.com/Qiskit/qiskit.org/assets/55488549/2cab9d30-0c17-4fc7-9b5c-3cf4251d065d

Fix- Changed the EcosystemTestTable toolTip content background-color to dark

---

constants/summerSchool2023Content.ts
pages/events/summer-school-2023.vue

Following requests from Aaliyah (Community Event Manager), we should disable the registration CTA at first, so we can soft launch the page. Once the event is live, we can make a small PR to update the CTA.
Note: we've done this in the past, w/ previous summer school events. I also shared this preview link w/ Aaliyah and she gave it a 👍🏼 
- removed eventbrite links for now
- updated CTA to use `kind="secondary"`
- used css to hide link icon
https://qiskit-org-pr-3228.dcq4xc5i083.us-south.codeengine.appdomain.cloud/events/summer-school-2023

feat(qgss23): temp disable cta

---

constants/summerSchool2023Content.ts

Addresses content update from Aaliyah shown here:
https://github.com/Qiskit/qiskit.org/assets/6276074/d138f4a3-9f42-4a1d-a076-27d1048a31d6
- corrected N. Bronn's session from `Lecture` to `Lab`, as shown in the doc
- added 2 Live Q&A rows to the curriculum table

feat(qgss23): update curriculum

---

pages/events/summer-school-2023.vue

Closes #3233 
- Use full image path
**If you have a Twitter account**
1. Use the [Twitter Card Validator tool](https://cards-dev.twitter.com/validator), and paste in the 
2. Paste in the Summer School 2023 preview URL `https://qiskit-org-pr-3234.dcq4xc5i083.us-south.codeengine.appdomain.cloud/events/summer-school-2023` 
**If you don't have a Twitter account**
1. Use a tool like [Tweetpik's Twitter Card Validator tool](https://tweetpik.com/twitter-card-validator)
2. Paste in the Summer School 2023 preview URL `https://qiskit-org-pr-3234.dcq4xc5i083.us-south.codeengine.appdomain.cloud/events/summer-school-2023`

fix: use full img path for twitter meta

---

components/Learn/LearnCoursePagesSection.vue
components/Metal/MetalDarkHeader.vue
components/Ui/UiCard.vue

Quick fix for https://github.com/Qiskit/qiskit.org/issues/3226
@eddybrando - feel free to dismiss / close this PR if you have a better solution
- for images that aren't properly populating into their `/ipx` directory, I commented out the `<nuxt-img>` implementation, and used the regular `<img>` tag instead, for now. 
- for the `MetalDarkHeader` svg static src, I removed the `format="webp"`, after borrowing the idea from [this issue](https://github.com/nuxt/image/issues/822#issue-1705359329) in the Nuxt Image repo.
```bash
git checkout fix/broken-imgs
npm run generate
nuxt start
```
Then visit the following pages:
- http://localhost:3000/learn/course/basics-quantum-information
- http://localhost:3000/metal
- http://localhost:3000/events > Past events tab

fix broken imgs

---

pages/ecosystem.vue

Fix https://github.com/Qiskit/qiskit.org/issues/3273
Fix https://github.com/Qiskit/qiskit.org/issues/2927
- Now the tiers are on tabs
- A search bar is added. Right now is only searching on the card description
Go to https://qiskit-org-pr-3278.dcq4xc5i083.us-south.codeengine.appdomain.cloud/ecosystem
- Tiers tabs should work
- Each tab only shows the members that are on that tier
- Search works both for searching on the description and on the title
**Out of scope**
- A solution when there are no results on the search

feat(ecosystem): move tiers to tabs and add search bar

---

components/Advocates/AdvocatesItemCard.vue
components/Events/EventsItemCard.vue
components/Landing/HeroMoment/LandingHeroMomentComponent.vue
components/Landing/LearnSection/LandingLearnSectionCard.vue
components/Landing/QiskitCapabilitiesSection/LandingQiskitCapabilityCard.vue
components/Metal/MetalCapabilitiesSection.vue
components/Metal/MetalDarkHeader.vue
components/Metal/MetalFeatureCard.vue
components/Ui/UiCard.vue
components/Ui/UiMosaic.vue
constants/summerSchool2023Content.ts
hooks/event-conversion-utils.ts
pages/events/index.vue
pages/events/summer-school-2023.vue
types/events.ts
types/uiComponents.ts

Added alt descriptions to all images on the website. Some of them are dynamic, some are not. Following the guidelines in [W3C](https://www.w3.org/WAI/tutorials/images/) on Images, those icons or images that were only meant to be decorative, have been assigned the alt value "", `alt=""` .
This PR closes #3189 
Alt descriptions where added to the following pages:
- Background image from header (_Drawing of two people working on a Quantum Computer_)
________________________
- Icons on the capabilities section (empty string)
________________________
- image from the learn with qiskit section
- Regular events: alt text includes the name of the event 
________________________
- Seminars: alt text reads the name of the speaker + photo
________________________
- No events found
- Photographs from …

Add alt text to current images

---

components/Learn/LearnStartLearningSection.vue

Fixes [#3302](https://github.com/Qiskit/qiskit.org/issues/3302) Corrected the spelling for Massachusets in the Learn Page.
Simply corrected the word in the LearnStartLearningSection.vue file.

Fixed spelling on Massachusets

---

components/Footer/FooterSection.vue

This PR increases the space between the text links in the footer in order to have safe tab targets.
Closes #3198
We conducted a Lighthouse report in https://pagespeed.web.dev/ and it flag some tab targets (the footer links) which were not sized properly:
As pointed out in https://developer.chrome.com/docs/lighthouse/seo/tap-targets/, the tab targets should be at least 48x48 in size or have enough spacing between each other.
This PR changes the padding for margin to avoid increasing the vertical size of the tab target and increasing the space to the next footer link, and also increases the margin from 8px to 12px.
A Lighthouse audit conducted locally in the Chrome dev tools didn't flag the tab targets after the change.
Before:
After:

fix(footer): increase tap targets space

---

components/Events/EventsSummerSchoolFaq2022.vue
components/Events/EventsSummerSchoolFaq2023.vue
components/Footer/FooterComponent.vue
components/Landing/HeroMoment/LandingHeroMomentComponent.vue
components/Landing/HeroMoment/LandingHeroMomentVersionInfo.vue
components/Landing/QiskitCapabilitiesSection/LandingQiskitCapabilitiesSectionComponent.vue
components/Learn/LearnMegaMenu.vue
components/Learn/LearnStartLearningSection.vue
components/Metal/MetalIntroSection.vue
content/ecosystem/members.json
nuxt.config.ts
pages/events/seminar-series.vue
pages/events/summer-school-2023.vue
pages/learn/course/algorithm-design.vue
pages/learn/index.vue
pages/learn/summer-school/quantum-simulation-summer-school-2022.vue

Fixes #3235
I have used the `public.siteUrl` variable already existing in the nuxt config to change the links in the components that reference the `https://qiskit.org`.
This change uses the `useRuntimeConfig` method. It does not change the links under the `constant` folder (because they are supposed to be constants).

change qiskit.org for config variable in vue components

---

error.vue

Fixes #3331 
https://qiskit-org-pr-3332.dcq4xc5i083.us-south.codeengine.appdomain.cloud/test
For some reason, when using `<nuxt-img>` and `npm run generate`, we're not having cat images generate in the optimized folders. I tried the following:
- testing a static image (not a dynamically created image), for example `cat1.png`
- upgrading the dependency and testing
- specifying "ipx" as the `provider` in nuxt.config
- disabling all nuxt-img instances, and leaving the `error.vue` instance, to see if it would render
In all these cases, the dynamically generated `cat<number>.png` image doesn't get transformed into the `.output/public/images/*` directories... 
(I _think_ it could be because the error.vue page isn't within the `/pages`? directory)
This PR will revert to using a normal `<img>` …

feat(error-page): fix broken images

---

components/Ecosystem/EcosystemItemCard.vue
components/Ui/UiCard.vue
pages/ecosystem.vue

Closes https://github.com/Qiskit/qiskit.org/issues/3323
Fixes https://github.com/Qiskit/qiskit.org/issues/3120
https://qiskit-org-pr-3322.dcq4xc5i083.us-south.codeengine.appdomain.cloud/ecosystem
- adds filtered results count to each tab
- abstracted repeated code in `filteredMembers` and `getFilteredResultsCount`, into `filterMembers` function
- removed the notion of tooltip tags, from card tags
- instead, using `primaryTag`
- showing dynamic filtered resuls count in each tab
- showing the relocation of the tier description (to beneath the tab)
- showing fixed gutter / responsive issue, caused by Tooltip Tag
https://github.com/Qiskit/qiskit.org/assets/6276074/8d0b1aea-592b-4839-85d0-ab80ea686e70

[ecosystem]: add results count to tab and relocate description

---

.gitignore
Dockerfile
nginx.preview.conf

Fixes #3321 
New Dockerfile that builds the site and serve it with nginx instead of nodejs.
AIRTABLE_API_KEY is now required for build the site.

new preview build to generate static site

---

components/Landing/HeroMoment/LandingHeroMomentComponent.vue
components/Metal/MetalBuildingSection.vue
constants/summerSchool2022Content.ts
constants/summerSchool2023Content.ts

"open source" -> "open-source"
([Reference](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/o/open-source))

Hyphenate open-source when used as adjective

---

hooks/ecosystem-conversion-utils.ts
pages/ecosystem.vue

- Removes randomization/shuffling of ecosystem members (since we're ordering them by `name`, by default)
- updates the `sortBy` implementation, so uppercase & lowercase are factored in the alphabetic order
https://github.com/Qiskit/qiskit.org/assets/6276074/d0243b1f-ac20-4883-9246-755ed781c073
(showing that sorting works alphabetically)
https://github.com/Qiskit/qiskit.org/assets/6276074/4881ba32-d3a5-43ef-8795-e14b8e8e7f29

[ecosystem]: remove shuffling and fix sorting

---

components/Ecosystem/EcosystemItemCard.vue

Fixes small alignment issue mentioned in [this comment ](https://github.com/Qiskit/qiskit.org/pull/3284#issuecomment-1598825276)
- remove the `cds--row` class because it was only used for its display flex 
- also, because when updating styles, I didn't want to target `.cds--row`
- used ecosystem card specific class name (`.__details`, which include license and GH stars for the card)
- added styles to respond at smaller viewports
- review styles please 
https://github.com/Qiskit/qiskit.org/assets/6276074/3e750f77-5450-4e98-8429-e2db09c0fbb8

feat(ecosystem-item-card): update alignment

---

error.vue

Fixes #3361 
Co-authored by: @y4izus 
- add a computed value for checking if the 404 `isDocumentationError`
- if so, we render the back to Documentation CTA
- else, show the normal back to Qiskit org home page CTA
- unfortunately, the preview branch doesn't produce the Nuxt error page, and only results in nginx server errors
(Showing dynamic error pages for a `500`, `404` from `/documentation/`, and regular `404`)
https://github.com/Qiskit/qiskit.org/assets/6276074/737ae425-028e-42e4-b694-6fe064aef9ba

feat(error-page): single cta w/ separate handling for docs errors

---

components/Ecosystem/EcosystemItemCard.vue
hooks/ecosystem-conversion-utils.ts
pages/ecosystem.vue

This PR improves the performance of the ecosystem page when changing the selected tier, the category filters or the sorting option.
We are still able to improve our performance further by moving some data formatting functions from Vue components to the fetching function that stored external data.
I still think that we can continue improving the performance, but we'll have to dig deeper. This might be a task for a later point in time.
Fixes #3370 
I used [computed properties instead of methods](https://vuejs.org/guide/essentials/computed.html#computed-caching-vs-methods) to leverage caching based on the reactive properties.
I also avoided to render the content of the tabs that were not active.
I also changed the order in which we performed certain operations on the members list to optimise …

perf(ecosystem): quicker list changes

---

constants/fallFest2022Content.ts
constants/summerSchool2022Content.ts
constants/summerSchool2023Content.ts

Fixes #3345 
Replaces broken links found in 3 areas

fix: replace broken links

---

content/providers/list/5.multi-platforms.yaml

Closes #3390 
Replaced the broken link on the SuperstaQ's Github link.

Fixed SuperstaQ Github Link

---

components/Ui/UiCodeSnippet.vue
content/providers/list/5.multi-platforms.yaml

Fixes #3174
Co-authored-By: @jackoconnordev
We use `br` to create the empty lines and have them preserved in the UI.
We also simplify the computed property `codeLines`.
Finally, we add some syntax fixes in the `content/providers/list/5.multi-platforms.yaml`, pointed out by @jackoconnordev in https://github.com/Qiskit/qiskit.org/pull/3445.

fix(code-snippet): preserve empty lines

---

error.vue

Ensure that the documentation link gets treated as an external link logically.
This PR fixes the `/documentation` link in the 404 pages.
Error pages that pointed to `/documentation` had a non-working CTA. We needed to pass the absolute URL (`https://qiskit.org/documentation/`) to ensure that our links' logic treats this link as an external link logically instead of attempting to use internal Nuxt routing logic.
In the preview build (or locally), go to a page like `/documentation/this-page-does-not-exist` to get an error page with the documentation CTA, and test if the CTA works when clicked.

fix(404): documentation link

---

pages/learn/course/multiple-qubits-and-entanglement.vue
pages/learn/course/quantum-protocols-and-quantum-algorithms.vue
pages/learn/course/quantum-states-and-qubits.vue
pages/learn/summer-school/quantum-computing-and-quantum-learning-2021.vue

Part of https://github.com/Qiskit/qiskit.org/issues/3473
- removed links that we know take users to an unwanted URL

fix: remove incorrect links to readings

---

constants/summerSchool2023Content.ts
pages/events/summer-school-2023.vue

Closes #3476 
- `See you soon` --> `See you next year!`
- Remove the `register now CTA`
- Remove the `View the event` CTA in event card

3476 summer school remove register cta

---

components/Ui/Link/UiLink.vue

When linking to external links, we want to preserve `noopener` but remove `noreferrer`.
This PR removes the [`noreferrer`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/noreferrer) keyword for external links since we want to be able to use the `Referer` header.
Closes #3514
We instruct NuxtLink explicitely to only use `noopener` for external links.
https://nuxt.com/docs/api/components/nuxt-link

feat(ui-link): remove `noreferrer`

---

content/providers/list/2.hardware.yaml
content/providers/quick-start/data.yaml

This patch updates the AQT (Alpine Quantum Technologies GmbH) provider data and quickstart examples.
Due to the deployment of a new portal, release [0.17.0](https://pypi.org/project/qiskit-aqt-provider/0.17.0/) of the `qiskit-aqt-provider` package is not backwards compatible. Also, code infrastructure has been renewed and the documentation is now hosted in the Github Pages attached to the code repository.
cc @fg-aqt

content/providers: update AQT data and examples

---

pages/events/fall-fest.vue

- Corrected the table scroll, now the "Qiskit Fall Fest: Extension Events" title and the description underneath it doesn't scroll down with the table.

table scroll corrected in new branch

---

error.vue

Fix #3586 
Links on the 404 page has been updated.
Note: the styles on this solution are different from the one on [figma](https://www.figma.com/file/0Je6YtTaizU1Y7lCubTenn/Qiskit.org-page-updates?type=design&node-id=808-1393&mode=design&t=2MU9bzfRrVA4FtPA-0) because I'm using the components we have

Updates links on the 404 page
