Qiskit/qiskit.org

- SUPPORTING-COLLABORATORS.md
> adding Collaborators

- src/app-shell.html
> qiskit-sdk-py > qiskit-core

- locales/de/app.json
Hi,
this PR contains new German translations for Entanglion section.
Albert
> Adding new German translations - Entanglion

- locales/de/app.json
Hi,
this PR adds the German translation for Aqua chemistry from PR #42.
Cheers, Albert
> add German translation for Aqua chemistry

- src/components/page-aqua.js
> Update Aqua example

- locales/en/app.json
- src/components/page-aqua.js
A few Aqua updates from @pistoia.
> Aqua updates

- locales/de/app.json
slight improvements in German subtitle following #59 
@abdonrd
> follow-up fix from English version

- src/components/page-aqua.js
Update the chemistry documentation link to point to https://qiskit.org/documentation/aqua/chemistry/qiskit_chemistry.html
> Update chemistry documentation link

- locales/de/app.json
- locales/en/app.json
- src/components/page-home.js
> Put citation section

- src/components/app-shell.js
Used JavaScript Date to get automatically the year.
Fixed #97
> Update year on footer

- src/components/page-ignis.js
Resolved some issues with the code example on Ignis page.
Fixes #101
> bug fixed on code example

- src/components/page-ignis.js
This PR closes #105 
Ignis stat section updated:
> Update ignis stack

- src/components/page-aer.js
This PR closes #104  
The updated Aer Stack section looks like this:
> Update Aer stack

- src/components/page-home.js
> Update StackExchange link

- src/components/app-shell.js
> change tutorials link

- src/components/app-shell.js
> change tutorials broken link on offcanvas menu

- gulpfile.js
> change offering interface

- gulpfile.js
- index.html
- src/components/app-shell.js
- src/components/page-aer.js
- src/components/page-aqua.js
- src/components/page-fun.js
- src/components/page-home.js
- src/components/page-ignis.js
- src/components/page-terra.js
- src/components/page-vscode.js
- src/helpers/track-events.js
Added track clicks and events from the user interactions with the website.
> Feature: Track events by Analytics

- gulpfile.js
> change productTitle

- src/components/page-home.js
> update slack link for one that will not expire

- src/components/page-aqua.js
- change `qiskit_chemistry` to `qiskit.chemistry` in example code's import statement
- minor adjustment on the algorithm listing
> Minor fixes on Aqua page

- src/components/app-shell.js
- src/components/page-aer.js
- src/components/page-aqua.js
- src/components/page-fun.js
- src/components/page-home.js
- src/components/page-ignis.js
- src/components/page-terra.js
- src/components/page-vscode.js
- src/helpers/track-events.js
Remove forbidden properties from custom events
> bugfixed on tracking analytics

- src/components/page-aqua.js
Added the github repo button for Qiskit Aqua Chemistry GUI, following the style lines of the other sections.
This PR closes #144
> Added button for Aqua GUI

- src/helpers/track-events.js
added url path to action on track button clicks
> Update Analytics tracking code

- gulpfile.js
related to #174 
Fixed copy file issue
> fixed file copy

- locales/en/app.json
- src/components/page-ibmqp.js
- src/router.js
This commit fixes the link to Access IBM Q Systems docs in IBM Q Account.
> Fix link in IBM Q Account

- src/components/app-shell.js
This commit fixes the redirection bug in IBM Q Account
> Bug in redirection to IBM Q Account

- src/components/page-home.js
This PR fixes the links in news description of home page. 
Fixes #217
> Fixed the links in News Box Description

- locales/en/app.json
Update text of "Coding with Qiskit" to "Qiskit on Youtube"
> Update Coding with Qiskit to Qiskit on Youtube

- locales/en/app.json
- src/components/page-home.js
Fixes #285 
**Before removing citation section:**
**After:**
> Removes citation section from front page

- index.html
> Add hotjar snippet to qiskit.org

- src/components/page-home.js
> Slack invite URL has expired on landing page

- src/router.js
- textbook/index.html
> Redirect qiskit.org/textbook to community.qiskit.org/textbook

- .github/ISSUE_TEMPLATE/bug_report.md
> Create a template for bugs issues

- .travis.yml
- components/headers/LegacyPresentation.vue
- components/menus/QiskitOrgMenu.vue
- components/qiskit/SyntaxHighlight.vue
- constants/menuLinks.ts
- mixins/segment-mixin.ts
- pages/ibmqaccount.vue
- pages/index.vue
- plugins/segment-analytics.ts
- tests/plugins/segment-analytics.spec.ts
Fix #368
Now there are two architectures for Analytics:
* A legacy one based on a plugin.
* A new one based on a mixin (developed in #361).
Consolidation of both architectures will happen in #364.
> Change CTA tracking to the new format

- nuxt.config.ts
Fix #391
According to the default implementation of Nuxt's `scrollBehaviour`
function, it seems `triggerScroll` is used for ensuring all the
components are available before scrolling.
Did not found official references to it. Sent a question to the Nuxt
team for clarifying if it is part of the public API:
https://cmty.app/nuxt/nuxt.js/issues/c10206
At the moment, we are adapting the default scroll behaviour to add
smooth navigation. Default scroll behaviour can be found at:
https://github.com/nuxt/nuxt.js/blob/e3ba6c290dd60e1a8c5b7daec72982a667a7fe04/packages/vue-app/template/router.scrollBehavior.js
> Ensure components are rendered before scroll.

- .eslintignore
- .gitignore
- CONTRIBUTING.md
- README.md
- deploy/deploy_cos.sh
- nuxt.config.ts
> Restore `dist` as the output folder

- nuxt.config.ts
> Filter README.md out when listing files

- content/events/africa.md
- content/events/asia.md
- content/events/camp-2020.md
- content/events/europe.md
- content/events/finland-unconference.md
- content/experiments/quantalier.md
- content/experiments/quantum-dice.md
- content/index/advocate-program.md
- pages/aqua.vue
- pages/ibmqaccount.vue
- pages/ignis.vue
- pages/terra.vue
- plugins/segment-analytics.ts
Fix #420 
I did not update "IBM Q Account" yet since we need to double-check with the Qiskit product team how to handle that name.
> Update IBM Q to IBM Quantum

- assets/scss/layout.scss
- nuxt.config.ts
- package-lock.json
- package.json
- plugins/carbon.ts
Closes #428 
Add Carbon components to project to start working with them.
> ISSUE-428 Add Carbon components

- components/cards/EventCard.vue
- content/events/events-previews.json
- pages/events/index.vue
Fix #434 
Although you can already see the list of the event cards, this PR is related only to the logic. Concerns related to the design will be in another issue
> List all events

- pages/index.vue
> Make Qiskit Camp Vermont dates "TBD"

- assets/scss/carbon/community-theme.scss
- assets/scss/mixins.scss
- assets/scss/theme.scss
- components/MdContent.vue
- components/advocates/MapSection.vue
- components/cards/AdvocateCard.vue
- components/cards/ExperimentCard.vue
- components/cards/ExperimentCarousel.vue
- components/education/TextbookPreview.vue
- components/features/CompactFeature.vue
- components/headers/CommunityHeader.vue
- components/headers/ExperimentHeader.vue
- components/menus/InnerNavigation.vue
- components/sections/PageSection.vue
- pages/advocates/index.vue
- pages/education/index.vue
- pages/events/_slug.vue
- pages/experiments/index.vue
Fix #455 
It also fixes individual event pages although not by incorporating Carbon since they need a total re-work and does not pay off.
> Use Carbon infrastructure in Community pages

- package-lock.json
- pages/index.vue
> Add activity for kids

- components/cards/EventCard.vue
Fix #478 
Note that this a fast solution. It will be the final solution when #479 is done
> Event card working for both external and internal links

- components/cards/EventCard.vue
> Opens event in a new tab

- constants/filters.ts
- content/events/past-community-events.json
- content/events/upcoming-community-events.json
- hooks/event-conversion-utils.ts
- nuxt.config.ts
- package-lock.json
- pages/events/index.vue
- store/modules/events.ts
> Updates location categories

- pages/events/index.vue
> Adds placeholder when no events

- hooks/event-conversion-utils.ts
Fix #516 
Let's merge in the end, when there are more events ready for publishing.
> Retrieve the event picture and take published field into account

- components/cards/EventCard.vue
- content/events/past-community-events.json
- content/events/upcoming-community-events.json
- hooks/event-conversion-utils.ts
- pages/events/index.vue
- store/modules/events.ts
- tests/hooks/event-conversion-utils.spec.ts
- tests/store/events.spec.ts
> Rename location into region, and place into location

- pages/events/index.vue
> Replace the placeholder text

- components/cards/EventCard.vue
- pages/events/index.vue
> Temporal events mobile version

- tests/hooks/event-conversion-utils.spec.ts
Follow-up of #531 attending review requests.
> Implement request changes

- components/advocates/AdvocateCard.vue
- pages/advocates/index.vue
> Refactor AdvocateCard and use BEM

- components/ui/CompactFeature.vue
- pages/advocates/index.vue
> Refactor CompactFeature to use BEM

- components/ui/SoftwareStack.vue
- pages/aer.vue
- pages/aqua.vue
- pages/ibmqaccount.vue
- pages/ignis.vue
- pages/terra.vue
> Refactor SoftwareStack and uses BEM

- components/ui/Media.vue
> Refactor Media component and use BEM

- components/ui/SyntaxHighlight.vue
- pages/aer.vue
- pages/aqua.vue
- pages/ibmqaccount.vue
- pages/ignis.vue
- pages/terra.vue
> Refactor SyntaxHighlight component and use BEM on it

- README.md
- constants/menuLinks.ts
- content/events/europe.md
- content/index/join-slack.md
- pages/index.vue
This PR updates the slack invites in a few different spots to the snippet: http://ibm.co/joinqiskitslack
> Update slack link

- pages/events/index.vue
Fix #612 
Doing better would require rethinking the height of the header and the video itself (#446) to avoid strange cuts of the content.
> Adjust height correction for the different breakpoints

- components/landing/LandingCta.vue
- components/landing/TheFeatureMosaic.vue
- components/landing/TheHeroMoment.vue
- components/landing/VersionInfo.vue
- pages/index.vue
Fix #619
Wait until solving #629 and rebase.
> Review the layout of the hero moment and mosaic together

- constants/appLinks.ts
- pages/index.vue
Fix #593
We should hold merging until the link is online.
> Announce virtual guide

- components/layouts/TheBanner.vue
- components/layouts/banners/TheBlackLivesMatterBanner.vue
- layouts/default.vue
This PR introduces the always useful banner component motivated and inspired by the GitHub banner on the same topic. We need our copy, here it is a placeholder.
> Acknowledge our support to Black lives matters movement

- components/layouts/PageFooter/index.vue
- constants/menuLinks.ts
> Removes career section

- content/events/summer-school.md
Add barebones details of Qiskit Global Summer School
> Add barebones details of Qiskit Global Summer School

- components/layouts/TheMenu/index.vue
- constants/menuLinks.ts
- mixins/menu.ts
- static/images/qiskit-new-logo-purple.svg
> New menu implementation

- assets/scss/layout.scss
- components/layouts/PageFooter/FooterSection.vue
- components/layouts/TheMenu/MobileMenu.vue
- components/layouts/TheMenu/SidebarMenu.vue
- components/layouts/TheMenu/index.vue
- constants/menuLinks.ts
- plugins/carbon.ts
Fix #669 
Rebase after merging #662
> Implementation of the mobile version of the menu

- content/events/summer-school.md
Incorporate Global Summer School V3 page changes
> Incorporate Global Summer School V3 page changes

- content/events/summer-school.md
Incorporate Global Summer School V4 page changes
> Incorporate Global Summer School V4 page changes 

- components/landing/TheHeroMoment.vue
> Hero description styles

- pages/index.vue
> Fixes "what qiskit can do" description syles

- components/landing/QuickStart/index.vue
> Deletes quick start section on small and medium devices

- components/landing/QuickStart/StartOnTheCloud.vue
> Fix styles on "start on the cloud" section

- components/landing/QuickStart/StartLocally.vue
> Quick install logic

- components/landing/TheLearnSection/LearnCard.vue
- constants/menuLinks.ts
- content/events/finland-unconference.md
- pages/learn.vue
> Add learn page to the IA

- components/learn/TheCarefulExplanationForAdvanced.vue
- components/learn/TheCarefulExplanationForBeginner.vue
- new-content/learning-resources/qiskit-blog.md
- new-content/learning-resources/textbook.md
- new-content/learning-resources/tutorials.md
- new-content/learning-resources/video-series.md
- pages/learn.vue
- store/index.ts
- store/modules/learning-resources.ts
> Add filtering logic through a Vuex module learningResources

- new-content/learning-resources/qiskit-blog.md
- new-content/learning-resources/textbook.md
- new-content/learning-resources/tutorials.md
- new-content/learning-resources/video-series.md
- pages/learn.vue
> Implement mobile layout for the learn page

- components/layouts/TheMenu/MobileMenu.vue
- components/ui/AppLink.vue
- constants/menuLinks.ts
- mixins/menu.ts
> Quick implementation of a mobile second level menu

- constants/menuLinks.ts
- textbook/index.html
> Review footer links

- components/landing/TheHeroMoment/index.vue
> Hero text not to overlap hero image

- package-lock.json
- package.json
- pages/advocates/index.vue
Fix #726 
Hold until July, 15th.
> Re-open call for advocates

- components/landing/TheHeroMoment/index.vue
> Gets pronuntiation for qiskit /kisskit/ or /cuiskit/ 50% of times

- components/landing/TheQuickStart/StartOnTheCloud.vue
> Replaces old start online text with new one

- components/landing/TheFeatures/TheFeatureMosaic.vue
Fix #762 
Quick fix: The main image it's still lazy load but we force the second image on medium and small devices. This second image is not lazy load
> Sets proper background image for algorithms on feature mosaic

- components/layouts/TheMenu/index.vue
- mixins/menu.ts
> Uses different color in the logo for active and non active states

- assets/scss/layout.scss
- nuxt.config.ts
> Scrolls to the top when changing the page

- components/ui/PageHeader.vue
- components/ui/RelevantWord.vue
- constants/menuLinks.ts
- mixins/menu.ts
- pages/learn.vue
- pages/overview.vue
> Overview header

- pages/overview.vue
> Creates the layout for overview page

- components/overview/ContentSection.vue
- pages/overview.vue
> Create a generic container for sections

- components/overview/TableOfContents.vue
- pages/overview.vue
> Create sticky menu

- components/overview/AccordionLayout.vue
- pages/overview.vue
> Fix image sizing in the overview page

- components/landing/TheQuickStart/StartLocally.vue
> Fix quick install line when installing stable version on Linux

- components/learn/TheLearnHeader.vue
- components/learn/TheLearningResourceList.vue
- pages/learn.vue
Fix #770
Further componentization is possible to isolate the filtering behaviour. However, this first componentization address the relatively high complexity of the presentational aspects of the filtering list.
> Split learn pages in components

- components/overview/TheTableOfContents.vue
- constants/overviewContent.ts
- pages/overview.vue
> Connect the TOC with the URL fragment and section visibility

- components/overview/AccordionLayout.vue
- constants/overviewContent.ts
Fix #852 
This PR also fix the size of images on the overview page for large devices
> Updates on overview page copy

- assets/scss/blocks/copy.scss
- components/landing/TheFeatures/TheFeatureMosaic.vue
- components/landing/TheHeroMoment/index.vue
- components/landing/TheLearnSection/LearnCard.vue
- components/landing/TheQuickStart/StartLocally.vue
- components/overview/ContentSection.vue
- components/overview/TheTableOfContents.vue
> Update body copy size

- README.md
- app/router.scrollBehavior.js
- nuxt.config.ts
> Isolate router.scrollBehavior into its own file

- assets/scss/layout.scss
> Remove overflows different than visible (default value) for root and wrapper elements

- components/landing/LandingCta.vue
- components/ui/SyntaxHighlight.vue
Fix #609 
Background in buttons now makes a swipe transition on hover.
> Swipe background effect

- components/landing/LandingCta.vue
- components/ui/AppCta.vue
#909 
Arrows in links now move slightly
> Link arrow animation

- components/events/TheEventsHeader.vue
- components/learn/TheLearnHeader.vue
- components/ui/ThePageHeader.vue
- pages/events/index.vue
- pages/overview.vue
Fix #933 
This PR also set the size for the title in the header instead of using `<br>` to calculate it
Note: Waiting for the list of words for the typewriting effect but the code review could start
> Implement events header

- components/events/EventCard.vue
- pages/events/index.vue
Fixes #942 
Note: I've used `width: calc(100% - #{$img-medium-width});` to size the `content` block because I didn't find a better way, but if you do, please, let me know :)
> Implement event card

- components/events/TheEventsHeader.vue
> Replace single quote with apostrophe

- components/events/TheEventsHeader.vue
Resolves #952 
Adding list of words.
> Update Events page header with list of words

- components/events/EventCard.vue
- pages/events/index.vue
Fixes #963 using updates to margin values.
> Fix mobile spacing inconsistency

- components/landing/TheHeroMoment/index.vue
- components/layouts/ThePageFooter/FooterSection.vue
- components/layouts/ThePageFooter/index.vue
- layouts/metal.vue
- pages/metal.vue
> Layout for dark page

- components/metal/BuildingSection.vue
> Fix mobile "keep in touch" section

- components/metal/BuildingSection.vue
- components/metal/EarlyAccessSection.vue
- pages/metal.vue
Fixes #997 (Early access section)
Fixes #998 (Adds Education content)
> Add Early access section

- constants/appLinks.ts
- pages/events/index.vue
Fix #972 
In this PR I have reused the `AppCta` component that has text color set to purple. I needed white text color and a size that fits the content, that is why I have used the `!important` CSS property.
I prefer not to override styles so [I propose a refactor](https://github.com/Qiskit/qiskit.org/issues/973) that includes links, ctas and buttons.
> Start event section

- components/metal/BuildingSection.vue
- pages/learn/_slug.vue
> Fixes text color on https://qiskit.org/learn/intro-qc-qh/

- .eslintrc.js
- components/metal/CapabilityCard.vue
- components/metal/FeatureCard.vue
- components/overview/TheTableOfContents.vue
- package-lock.json
- package.json
- pages/events/_slug.vue
- pages/learn/_slug.vue
Fix #1029
The linter was already enabled. This PR makes the linter to exit with error if there is a linting error. Take a look at the contribution guidelines for what to do when you encounter a linting error.
> Convert warnings into errors

- components/metal/CapabilitiesSection.vue
- components/metal/IntroSection.vue
> fix issue 1039

- tests/store/events.spec.ts
Adding test, based on the recommendation [here](https://github.com/Qiskit/qiskit.org/pull/951#discussion_r513782169)
> Add updateFilterSet test

- CONTRIBUTING.md
Fix #1032
Fix #1033
This is a forced PR for being able to review the contribution guidelines online.
> Add CONTRIBUTING.md for review

- pages/events/index.vue
> Align filter arrows on event page

- components/metal/MetalGrid.vue
> black tiling limited

- .github/CODEOWNERS
> Adds Goyo to codeowners file

- components/advocates/AdvocateCard.vue
- components/ui/AppCard.vue
- content/advocates/index/abraham-asfaw.md
- content/advocates/index/carmen-recio-valcarce.md
- content/advocates/index/hassi-norlen.md
- content/advocates/index/holly-cummins.md
- pages/events/index.vue
Fix #1088 
This PR affects AppCard, so the events card should be checked too.
> Update advocate card

- components/advocates/MeetTheAdvocates.vue
- components/ui/InfiniteScroll.vue
- mixins/scrollBetweenSections.ts
> Simple infinite scrolling implementation used on MeetTheAdvocates component

- constants/overviewContent.ts
> Correct spelling of "noise"

- components/ui/AppCard.vue
> Fix events cards title overflow

- package-lock.json
- package.json
> Update @nuxtjs/axios dependency

- hooks/event-conversion-utils.ts
Seems like with #526 closed, we don't need this
> Remove TODO about types

- components/landing/TheQuickStart/StartLocally.vue
- components/layouts/PageFooter/FooterSection.vue
- components/layouts/TheMenu/index.vue
- package-lock.json
- package.json
- pages/events/index.vue
> Update Carbon dependencies

- package-lock.json
- package.json
> Update ts-node dependency

- package-lock.json
- package.json
> Update cross-env dependency

- package-lock.json
- package.json
> Update jest dependencies

- .storybook/main.js
- components/ui/AppCard.stories.ts
- package-lock.json
- package.json
**Note:** This is only one part of https://github.com/Qiskit/qiskit.org/issues/884#issuecomment-733034345
---
As defined in #1144, the following Storybook add-ons are setup with this PR:
- [Accessibility](https://github.com/storybookjs/storybook/tree/master/addons/a11y)
- [Design / Figma](https://github.com/pocka/storybook-addon-designs)
---
Closes #1144
> Setup Storybook add-ons

- .github/workflows/test.workflow.yml
Fix #1172
If we merge it, we should [update the **`Required`** checks](https://github.com/Qiskit/qiskit.org/settings/branches):
> Parallelize jobs in GitHub Actions

- assets/scss/blocks/prerequisites.scss
- components/landing/TheQuickStart/StartLocally.vue
- components/landing/TheQuickStart/index.vue
- components/ui/SyntaxHighlight.vue
This PR changes the text colors `#6f6f6f` to `#343A3F` (_cool gray 80_) to improve accessibility.
---
Closes #1206
> fix: adjust text color to improve accessibility

- components/landing/TheFeatures/TheFeatureMosaic.vue
- components/landing/TheFeatures/index.vue
- components/ui/AppMosaic.vue
> Refactor feature mosaic

- components/events/EventCard.vue
- components/events/seminar-series/PastSeminarSeriesSection.vue
- components/events/seminar-series/SeminarSeriesDataTable.vue
- components/events/seminar-series/SeminarSeriesHeader.vue
- components/events/seminar-series/UpcomingSeminarSeriesSection.vue
- components/ui/AppCard.vue
- constants/appLinks.ts
- pages/events/seminar-series.vue
> Instrument seminar series page

- hooks/event-conversion-utils.ts
The name of the view has been changed and it should be updated
> Rename Seminar Series view

- constants/appLinks.ts
The link to request an event has changed, so this PR is for replacing it
> Replace events request link

- components/landing/TheQuickStart/StartOnTheCloud.vue
- components/landing/TheQuickStart/index.vue
- constants/appLinks.ts
Fix #1314 
I did also small modifications (uppercase, comma, ...)
> Updates copy on Quick Start component

- package-lock.json
- package.json
Reverts Qiskit/qiskit.org#1426
> Revert "Bump nuxt from 2.14.12 to 2.15.0"

- components/ui/AppContentSection.vue
- components/ui/AppIntroductoryContent.vue
- pages/overview.vue
This PR refactors "components/overview/ContentSection.vue" into a reusable component.
---
Closes #1460
> refactor: make ContentSection reusable

- assets/scss/blocks/copy.scss
- components/textbook-demo/StartLearningSection.vue
- components/textbook-demo/TextbookDemoHeader.vue
- components/ui/AppIntroductoryContent.vue
- components/ui/AppMegaDropdownMenu.vue
- constants/megaMenuLinks.ts
- constants/menuLinks.ts
- pages/overview.vue
- pages/textbook-demo/index.vue
> Implement Textbook demo feedback

- constants/appLinks.ts
> feat: update Quantum Lab URL

- components/textbook-demo/StartLearningSection.vue
- constants/appLinks.ts
- pages/textbook-demo/learning-paths/introduction-course.vue
> feat: create learning path page

- components/textbook-demo/LearningPathPagesSection.vue
> feat: add "segments" to links with hover effect

- components/textbook-demo/PrerequisiteMaterialSection.vue
> feat: add segments and URLs to "Prerequisite Material"

- components/ui/AppCard.vue
> fix: prevent card content overflow

- components/advocates/MeetTheAdvocates.vue
- pages/events/index.vue
- pages/events/seminar-series.vue
- pages/learn/index.vue
> fix: avoid TS2691 by removing extensions

- layouts/default-textbook.vue
> fix: display correct layout styles

- components/textbook-demo/PrerequisiteMaterialSection.vue
- components/ui/AppDescriptionCard.vue
- pages/textbook-demo/index.vue
> feat: DRY "Prerequisite Material" cards

- components/textbook-demo/ExternalRecommendedReadings.vue
- constants/appLinks.ts
- pages/textbook-demo/learning-paths/introduction-course.vue
> feat: add segments to "External Recommended Readings"

- components/textbook-demo/IntroductionCourseHeader.vue
- components/textbook-demo/LearningPathPagesSection.vue
- constants/appLinks.ts
- pages/textbook-demo/learning-paths/introduction-course.vue
> feat: add segment to Introduction Course header

- pages/photon.vue
This PR create the skeleton of the Photon LP.
The header isn't added yet since there is currently a PR in review with the new header components.
---
Closes #1599
> feat: create Photon skeleton

- components/layouts/TheMenu/index.vue
- package-lock.json
> Fix Community dropdown icon alignment in header

- components/photon/PhotonDirectionsSection.vue
- components/photon/PhotonRecommendationSection.vue
- components/ui/AppCta.vue
- components/ui/BasicLink.vue
- pages/photon.vue
- tsconfig.json
> feat: map section

- components/blockbuster/BlockbusterExplanationSection.vue
> BB Page content update

- components/landing/TheHeroMoment/index.vue
> Updated "Get started" Link

- pages/events/summer-school.vue
Small style update to fix issue shown below 👇
> Fix table spacing

- new-content/events/summer-school-2021.yaml
- Updating Resources CTAs
- adding URLs to missing hrefs
> Updating links

- new-content/events/summer-school-2021.yaml
- pages/events/summer-school.vue
The order of the sections in the `yaml` file is interpreted to display them accordingly.
> Section order in yaml matters

- new-content/events/summer-school-2021.yaml
- pages/events/summer-school.vue
Small PR to add subtitle to Summer School agenda section.
> Add summer school subtitle

- components/ui/AppCta.vue
- components/ui/AppDataTable.vue
- components/ui/AppMosaic.vue
- pages/events/physics-of-computation.vue
The event's team requested some changes on the content. Waiting for their review. DO NOT MERGE yet, please :)
> Content updates on the QC40 page

- pages/events/physics-of-computation.vue
This PR updates the content of the QC40 page.
---
Closes #1752
> feat: update QC40 content

- components/advocates/MeetTheAdvocates.vue
- components/landing/TheQuickStart/index.vue
- components/learn/TheLearningResourceList.vue
- components/ui/AppCard.vue
- components/ui/AppFieldset.vue
- components/ui/AppFiltersResultsLayout.vue
- components/ui/AppMosaicSection.vue
- pages/learn/index.vue
This PR adapts the learn page to support the new layout for the "max" breakpoint.
---
Closes #1761
> feat: learn page "max" breakpoint layout

- components/ui/AppCard.vue
- components/ui/AppFiltersResultsLayout.vue
- pages/events/index.vue
- pages/learn/index.vue
This PR adapts the learn page to support the new layout for the "max" breakpoint.
---
Closes #1816
> feat: events page "max" breakpoint layout

- constants/summerSchool2021Content.ts
This PR is for the event's team, to allow them to update the syllabus for the summer school page
> Updates summer school syllabus

- components/ui/AppFiltersResultsLayout.vue
> chore: remove no longer used prop

- components/textbook-demo/TextbookDemoHeader.vue
- components/ui/AppMegaDropdownMenu.vue
This PR updates the copy from "browse content" to "browse all content.
---
Closes #1845
> feat: update copy to "browse all content"

- content/learn/intro-qc-qh.md
> Replace lecture 19 private link with the public one

- constants/menuLinks.ts
> Adds code of conduct to the footer

- constants/megaMenuLinks.ts
Fix #1812 
Links updated to point to the internal beta.
> Mega dropdown menu links update

- constants/appLinks.ts
> Update Start Learning CTA link

- hooks/event-conversion-utils.ts
- store/events.ts
- tests/hooks/event-conversion-utils.spec.ts
- tests/store/events.spec.ts
> Update airtable and filters for the events page

- components/advocates/AdvocatesJoinSection.vue
> Add "join the program" CTA to the advocates page

- components/ui/AppPageHeaderWithCard.vue
- pages/events/physics-of-computation.vue
- pages/events/seminar-series.vue
- pages/events/summer-school.vue
This PR adapts the individual event pages to support the new layout for the "max" breakpoint.
---
Closes #1867
> Ev issue 1867 individual events max layout

- components/landing/TheHeroMoment/index.vue
- components/landing/TheQuickStart/StartLocally.vue
- components/landing/TheQuickStart/index.vue
- pages/index.vue
Closes #818 
Fixed some of the content typos/bugs reported in #818  which were not fixed already.
> Fixed content bug in qiskit.org

- components/textbook-demo/CoursePagesSection.vue
- components/textbook-demo/PrerequisiteMaterialSection.vue
- constants/appLinks.ts
- constants/megaMenuLinks.ts
> Replaces platypus with learn on links

- components/textbook-demo/CoursePagesSection.vue
- components/textbook-demo/PrerequisiteMaterialSection.vue
> Adapt to new course content

- package-lock.json
- package.json
- pages/textbook-beta/index.vue
This PR displays the banner in the Textbook homepage using the new `QiskitBanner` component.
Preview: https://qiskitorg-git-fork-eddybrando-ev-issue-1928-textb-dd907a-qiskit.vercel.app/textbook-beta
QiskitBanner source code: https://github.com/qiskit-community/qiskit-vue/tree/main/src/components/QiskitBanner
QiskitBanner Storybook: https://qiskit-community.github.io/qiskit-vue/?path=/docs/components-qiskitbanner--short-content
---
Closes #1928
> feat(banner): display banner in Textbook homepage

- components/advocates/AdvocatesJoinSection.vue
- components/events/EventCard.vue
- components/events/summer-school/FaqSection.vue
- components/landing/TheHeroMoment/VersionInfo.vue
- components/landing/TheHeroMoment/index.vue
- components/landing/TheLearnSection/LearnCard.vue
- components/textbook-demo/CoursePagesSection.vue
- components/textbook-demo/PrerequisiteMaterialSection.vue
- components/textbook-demo/StartLearningSection.vue
- components/ui/AppCard.vue
- components/ui/BasicLink.vue
- components/ui/SyntaxHighlight.vue
- constants/appLinks.ts
- constants/megaMenuLinks.ts
- constants/menuLinks.ts
- constants/segment.ts
- constants/summerSchool2021Content.ts
- pages/events/physics-of-computation.vue
- pages/events/seminar-series.vue
- pages/index.vue
- pages/textbook-beta/course/introduction-course.vue
- pages/textbook-beta/index.vue
- plugins/segment-analytics.ts
- tests/plugins/segment-analytics.spec.ts
This PR updates the structure of the data passed to Segment via the _properties_.
---
Closes #1511
> feat(segment): new Segment properties structure

- components/events/summer-school/FaqSection.vue
- components/metal/BuildingSection.vue
- components/textbook-beta/PrerequisiteMaterialSection.vue
- components/textbook-beta/StartLearningSection.vue
- constants/menuLinks.ts
- constants/summerSchool2021Content.ts
- content/learn/intro-qc-qh.md
- new-content/learning-resources/textbook-1-3.md
- new-content/learning-resources/textbook.md
This PR updates various links to point to the new Textbook Beta.
---
Closes #1947
> Update Textbook links

- components/landing/TheHeroMoment/index.vue
> Fix typo in index.vue

- nuxt.config.ts
Help to fix one of the #2014 warnings
> Remove deprecated NuxtJS mode option

- package-lock.json
Help to fix one of the #2014 warnings.
Browserlist data updated after run this command:
```
npx browserslist@latest --update-db
```
> Update the Browserlist Data

- .github/workflows/deploy.workflow.yml
- .github/workflows/test.workflow.yml
Fix #2018
Also use the same format in both workflows.
> Update `actions/setup-node` to v2 and enable npm cache

- pages/events/india-week-of-women-in-quantum.vue
Adds twitter card meta tag to show the summary of the event on twitter
> Adds twitter card meta tag

- constants/appLinks.ts
- pages/textbook-beta/summer-school/quantum-computing-and-quantum-learning-2021.vue
Based off the conversation and agreement by the team, we're updating the Textbook beta paths.
This PR is to update links that point to the Textbook beta.
> Update summer school links

- content/learn/intro-qc-qh.md
Replace the video link with a new one. #2286
> Video link doesn't work #2286

- components/landing/TheQiskitCapabilitiesSection/CodeCell.vue
- components/landing/TheQiskitCapabilitiesSection/index.vue
Fix: https://github.com/Qiskit/qiskit.org/issues/2350
> Code cell for new homepage

- pages/textbook-beta/course/machine-learning-course.vue
> update qml course url

- .github/workflows/deploy.yml
- .github/workflows/preview-cleanup.yml
- .github/workflows/preview-deploy.yml
- .github/workflows/test.yml
- .github/workflows/verify.yml
Also:
- Extract the node version to a env variable.
- Clean the naming to better read:
> Prevents GitHub Actions to be executed by forks

- .github/pull_request_template.md
Created a pull request template.
Closes #2455
The file name and location follows the guide in https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository.
- Create similar PR templates for the other projects' repositories.
- Update the "Pull requests" chapter in the **CONTRIBUTING.md** file.
- Create a discussion to decide whether to add a "PR Checklist" section and how if should be.
> feat: create pull request template

- pages/textbook-beta/course/machine-learning-course.vue
Just added a line explaining who worked on the qml course.
> Add contributors statement to qml course

- CONTRIBUTING.md
Updated the "Code review" chapter from the contribution guidelines file, adding a small sentence about the [recently introduced](https://github.com/Qiskit/qiskit.org/issues/2455) pull request template.
Closes #2471
> docs: add PR template information

- .github/workflows/preview-cleanup.yml
- .github/workflows/preview-deploy.yml
Avoid running the workflows to generate preview deployments for "dependabot" PRs.
Closes #2505
Co-authored-by: @abdonrd 
Added a check to the workflows to avoid running if the author is "dependabot".
> ci: deactivate dependabot previews

- components/ui/AppIntroductoryContent.vue
- constants/overviewContent.ts
- pages/overview.vue
Updated new links on the `/overview` page
Closes #2496 
https://qiskit-org-pr-2508.dcq4xc5i083.us-south.codeengine.appdomain.cloud/overview
- updated links in `overviewContent`
- added a `linkset` property for the `AppIntroductoryContent` component which allows for an array of links (to match design need)
- check that the implementation matches the [design update](https://www.figma.com/file/vxmMO1ii3qEQdYmohkmlC9/2496-overview-page-update?node-id=2%3A641)
- check that the links are working as expected
> update overview links

- content/advocates/advocates.json
- content/events/past-community-events.json
- content/events/past-seminar-series-events.json
- content/events/upcoming-community-events.json
- content/events/upcoming-seminar-series-events.json
- hooks/event-conversion-utils.ts
- store/events.ts
- tests/hooks/event-conversion-utils.spec.ts
This pull request fixes an issue with our way of filtering the Airtable events by date.
We were only taking into consideration the start date of the events. With this change, we will be taking also the end dates into account whenever it makes sense.
Closes #2518
Co-authored-by: @techtolentino 
Currently, we use an Airtable filtering function to fetch the events that are within a specified date range. But this filtering function is only taking into account the start date of the event.
We couldn't figure out a way to add conditional logic to filter sometimes for end dates and sometimes for start dates based on the data in the database and the requirements of the external function calling the fetching function. At least not on a simple way. There might be a way to do this with the filtering …
> fix(events): events date range filter

- components/ui/AppDataTable.vue
- components/ui/AppDataTableSection.vue
- constants/summerSchool2021Content.ts
- pages/events/india-week-of-women-in-quantum.vue
- pages/events/physics-of-computation.vue
- pages/events/seminar-series.vue
- pages/events/summer-school.vue
Refactor of the AppDataTable component as part of https://github.com/Qiskit/qiskit.org/issues/2503
This code also fixes and issue on the [summer school page](https://qiskit.org/events/summer-school/), where the table doesn't scroll and makes part of the page not fit the width of the page
On the mentioned issue, we need to have Carbon components on the AppDataTable and we need to be able to change their color. With the previous version of this component, we weren't allow to change the color because the `fill` property was overwritten when building the dynamic component for the cell inside AppDataTable.
After talking with @korgan00 , we thought the best option was to extract the definition of the cells to have more flexibility
I've refactored the tables on the following pages:
- [Summer …
> Refactor AppDataTable

- components/textbook-beta/ExternalRecommendedReadings.vue
This PR restores the deleted file "ExternalRecommendedReadings.vue" file so that the "External Recommended Readings" section is shown.
Closes #2565
Restored the file as it was just before it got deleted with https://github.com/Qiskit/qiskit.org/commit/7036e4b05aad26e74f53830704ac0035948de256.
Before (without section):
After (with section):
> fix: restore deleted component

- components/textbook-beta/CoursePagesSection.vue
Fixes https://github.com/Qiskit/qiskit.org/issues/2599
(smallest PR ever)
> change heading

- pages/textbook-beta/index.vue
Fixes #2616 
- removed Tutorials tile
- added Educators Program tile
https://qiskit-org-pr-2618.dcq4xc5i083.us-south.codeengine.appdomain.cloud/textbook-beta/#:~:text=View%20resource-,Helpful%20Resources,-Documentation
> add new helpful resource tile

- pages/textbook-beta/course/introduction-course.vue
- pages/textbook-beta/course/multiple-qubits-and-entanglement.vue
- pages/textbook-beta/course/prerequisites.vue
- pages/textbook-beta/course/quantum-protocols-and-quantum-algorithms.vue
- pages/textbook-beta/course/quantum-states-and-qubits.vue
Updated the external resources links to match the required label and url links as outlined in Figma.
Closes #2580 
Updated the references object on 4 pages.
> update external readings links

- pages/events/summer-school.vue
Fixes Summer School responsive issue
- adds class to `bx-grid` container
- gives `max-width` to container at smaller breakpoints, allowing the `AppDataTable` to overflow scroll 
- review small code updates
- review UI in branch preview
> Fix Summer School mobile responsiveness

- components/learn/LearnContentMenuSection.vue
- components/learn/LearnHeader.vue
- package-lock.json
- package.json
Fixes https://github.com/Qiskit/qiskit.org/issues/2645
- updated @qiskit/web-components package to get the style updates
- cleaned up HTML and dom structure to match current implementation on /textbook-beta
https://user-images.githubusercontent.com/6276074/171852330-aebe0aa5-30a8-428c-9c75-2b7093c4e08a.mov
> Update qiskit/web-component package clean up component html

- pages/ecosystem/index.vue
- pages/textbook-beta/course/introduction-course.vue
Closes #2637
Co-Authored-By: @HuangJunye
Sets an appropriate HTML meta description for the [ecosystems page](https://qiskit.org/ecosystem/).
Used https://nuxtjs.org/docs/features/meta-tags-seo/.
Just 1 file. Just 1 line. Read from left to right preferably.
> feat(ecosystem): set meta description

- pages/advocates/index.vue
Closes #2636
Co-Authored-By: @HuangJunye
Sets an appropriate HTML meta description for the [advocates page](https://qiskit.org/advocates/).
Used https://nuxtjs.org/docs/features/meta-tags-seo/.
Just 1 file. Just 1 line. Read from left to right preferably.
> feat(advocates): set meta description

- components/learn/LearnContentMenuSection.vue
- components/learn/LearnHeader.vue
- package-lock.json
- package.json
Fixes https://github.com/Qiskit/web-components/issues/103 
https://qiskit-org-pr-2655.dcq4xc5i083.us-south.codeengine.appdomain.cloud/learn/
- updated `@qiskit/web-components` package
- updated styles using css variables
- updated DOM structure for consistency
https://user-images.githubusercontent.com/6276074/172484695-3a2bcd39-09b9-44b9-b5c9-6cb534001d14.mov
> Update @qiskit/web-components and mega-menu-dropdown implementation

- constants/megaMenuLinks.ts
Removed an extra `introduction/` in url, fixes #2661
> Correct links to intro course

- components/learn/LearnContentMenuSection.vue
- components/learn/LearnHeader.vue
- package-lock.json
- package.json
Related to https://github.com/Qiskit/web-components/issues/99
Co-authored by: @abdonrd 
- used new version of `@qiskit/web-components` package
- cleaned/updated the way we use the component css variables
https://user-images.githubusercontent.com/6276074/175328640-de742d8b-f586-4a0d-8dad-3fbd20391528.mov
> use new qiskit/web-components version, clean variable usage

- .github/ISSUE_TEMPLATE/feature_request.yml
Closes #2679 
- removed alternatives
> update feature request template

- components/ecosystem/TestTable.vue
- components/ui/AppCard.vue
- pages/ecosystem/index.vue
There are 3 main enhancements to the test table in this PR:
- Make the test version table header dynamic, as not every project will be tested against terra (e.g. some might be tested agains nature)
- add tooltips to each test type to explain what it means (@1ucian0 @IceKhan13 I would appreciate your thoughts on the wording for these)
- add a new column with links where users can see the test logs for a specific test
> Ecosystem: Test table updates

- components/ecosystem/TestTable.vue
- content/ecosystem/members.json
- pages/ecosystem/index.vue
Fixes https://github.com/Qiskit/qiskit.org/issues/2715
Edited small bit of CSS so that tooltip doesn't get cutoff in test table
Before:
After:
> Ecosystem: Fix `TestTable` `overflow-x` bug

- package.json
This PR adds a script to test only changed files with Jest.
When developing locally, we can use `npm run test:changed` to run tests only on the changed files.
Reminder: You can also open your locally generated `coverage/lcov-report/index.html` file and see a detailed coverage report.
---
Related to https://github.com/Qiskit/qiskit.org/issues/2699.
> test: script to test only changed files

- constants/megaMenuLinks.ts
> fix broken link

- store/advocates.ts
Fixed Advocates Location Filter
Closes #2733 
With help from @techtolentino 
Before:
After:
> Fixed advocate page locations filter. Changed Australia to Oceania

- .github/workflows/verify.yml
This PR adds [Coveralls](https://coveralls.io/) reporting to the "Test" job in the "verify" workflow.
Related to https://github.com/Qiskit/qiskit.org/issues/2700
> ci: setup Coveralls

- pages/index.vue
I've capitalized the R in Qiskit Runtime in the banner at the top of the home page.  This change is consistent with its usage e.g. at the "Learn more" link in the banner and elsewhere in IBM Quantum documentation. (The banner was originally added in #2594.)
> Capitalize Qiskit Runtime in banner

- layouts/default-max.vue
- layouts/default.vue
- package-lock.json
- package.json
Update `@qiskit/web-components` to 0.9.2
- This PR will pull in a typo fix `Qiskit texboox` > `Qiskit Textbook`
- This PR will also add `documentation-` prefix to all links clicked from `Documentation` dropdown (see issue here: https://github.com/Qiskit/web-components/issues/161)
Most recent updates require the max-width to be set, since it defaults to `none`.
[Preview link](https://qiskit-org-pr-2796.dcq4xc5i083.us-south.codeengine.appdomain.cloud/)
> chore: bump ui-shell version

- constants/megaMenuLinks.ts
Adds the summer schools to the mega menu (basically the same as https://github.com/Qiskit/platypus/pull/1614).
> Add summer schools to mega menu

- components/learn/StartLearningSection.vue
Closes #2835 
- added static array of Syllabi (provided by Sanket)
- updated SCSS for responsive purposes
https://user-images.githubusercontent.com/6276074/195149279-1ef60d01-1917-4100-9815-902cdc8ee91a.mov
> Curated syllabi: Add Teach tab content

- components/events/fall-fest/UniversityDirectorySection.vue
- constants/fallFest2022Content.ts
Closes #2840 
https://qiskit-org-pr-2841.dcq4xc5i083.us-south.codeengine.appdomain.cloud/events/fall-fest
> [Qiskit Fall Fest] Update university info

- components/events/fall-fest/UniversityDirectorySection.vue
- constants/fallFest2022Content.ts
Closes https://github.com/Qiskit/qiskit.org/issues/2869
This PR makes an update to specific event dates, names, and links
https://qiskit-org-pr-2870.dcq4xc5i083.us-south.codeengine.appdomain.cloud/events/fall-fest
> feature(fall-fest): update content

- pages/events/index.vue
Fixes typo on events not found banner.
Closes #2962
> fix no events found typo

- Dockerfile
- layouts/default-max.vue
- layouts/default.vue
- layouts/metal.vue
- pages/index.vue
With this PR we now have PR previews working again.
1. Made some changes to the Dockerfile (similar to Saiba)
2. Fixed issues with the template files causing errors (needed `script setup`)
3. Added a small "Qiskit.org" text to see that the deployment works
Left to right. Top to bottom.
> ci: working PR previews

- components/events/EventCard.vue
- hooks/event-conversion-utils.ts
- pages/events/index.vue
Resolves https://github.com/Qiskit/qiskit.org/issues/2902
- pulls in event abstract field
- review how `event.abstract` string is passed into the `EventCard` (as slot)
```shell
npm run generate
npm run start
```
https://user-images.githubusercontent.com/6276074/217284332-2ac0f39d-593a-4250-99d2-21a88dcdc5f0.mov
> feat(events): add description to EventCard

- package-lock.json
- package.json
This PR updates the UI Shell web component to include the changes introduced in https://github.com/Qiskit/web-components/pull/201.
Updated the **package** and **package-lock** files.
> feat: update UI Shell

- CONTRIBUTING.md
- components/advocates/MeetTheAdvocates.vue
- components/events/summer-school/FaqSection.vue
- components/metal/JoinUsSection.vue
- constants/menuLinks.ts
Fixes https://github.com/Qiskit/qiskit.org/issues/2959
> Update slack invite link

- components/events/FollowCalendar.vue
- components/events/RequestEvent.vue
- pages/events/index.vue
> Segment tabs

- components/events/FollowCalendar.vue
- components/events/RequestEvent.vue
- pages/events/index.vue
Main changes code-wise include ading new two components to split the extra info section of the events page, FollowCalendar and RequestEvent. 
Also, refactored selectTab.
This PR closes #3003
https://user-images.githubusercontent.com/108661074/222767293-836f7435-cf5f-499f-affc-bbf686e88fd2.mov
> Extra info new components

- components/landing/TheQiskitCapabilitiesSection/CodeCell.vue
This PR fixes the issue with the content of the code cell on the homepage overflowing on small viewports horizontally.
Closes #3039
Set the `overflow-x` attribute to `scroll`.
Grab a coffee because it might take a while.
1. See the 1 line code change
2. Check that it works in the UI
> fix(code-cell): horizontal content overflow

- components/learn/ContentMenuSection.vue
- components/learn/DynamicBackgroundLogo.vue
- components/learn/ExternalRecommendedReadings.vue
- components/learn/PageHeader.vue
- components/learn/SketchedLogo.vue
- components/learn/StartLearningSection.vue
- components/ui/AppPageHeaderWithImage.vue
- components/ui/BasicLink.vue
- pages/learn/course/basics-quantum-information.vue
- pages/learn/course/introduction-course.vue
- pages/learn/course/multiple-qubits-and-entanglement.vue
- pages/learn/course/prerequisites.vue
- pages/learn/course/quantum-protocols-and-quantum-algorithms.vue
- pages/learn/course/quantum-states-and-qubits.vue
- pages/learn/index.vue
- pages/learn/summer-school/introduction-to-quantum-computing-and-quantum-hardware-2020.vue
- pages/learn/summer-school/quantum-computing-and-quantum-learning-2021.vue
- pages/learn/summer-school/quantum-simulation-summer-school-2022.vue
- types/learn.ts
This PR makes the necessary changes to all "learn" pages to make them work with Nuxt 3.
Closes #3030 
Preview links to check:
- https://qiskit-org-pr-3037.dcq4xc5i083.us-south.codeengine.appdomain.cloud/learn
- https://qiskit-org-pr-3037.dcq4xc5i083.us-south.codeengine.appdomain.cloud/learn/intro-qc-qh
- https://qiskit-org-pr-3037.dcq4xc5i083.us-south.codeengine.appdomain.cloud/learn/course/basics-quantum-information
- https://qiskit-org-pr-3037.dcq4xc5i083.us-south.codeengine.appdomain.cloud/learn/course/games-and-demos
- https://qiskit-org-pr-3037.dcq4xc5i083.us-south.codeengine.appdomain.cloud/learn/course/introduction-course
- https://qiskit-org-pr-3037.dcq4xc5i083.us-south.codeengine.appdomain.cloud/learn/course/machine-learning-course
- …
> refactor(learn): migrate to Nuxt 3

- components/ui/CodeSnippet.vue
Fixes #3042 
- Update styles to handle mobile overflow issue 
- removed styles that were breaking long code lines to new lines
- removed class name that was no longer being used
- test UI
- test the QuickStart code snippet w/ longer lines of code
https://user-images.githubusercontent.com/6276074/226784647-0d94fadc-a631-46cb-bded-93c2340eed0a.mov
> feat(code-snippet): update component overflow

- content/providers/cloud-simulators.json
- content/providers/hardware.json
- content/providers/local-simulators.json
- content/providers/multi-platforms.json
- content/providers/quick-start.json
- content/providers/runtimes.json
Resolves https://github.com/Qiskit/qiskit.org/issues/3047
Co-author: @eddybrando 
- Updates the JSON so that the component can recognize how the installation code should be multiline 
- cc: @HuangJunye (we'll need to update the json script to output this way)
https://qiskit-org-pr-3053.dcq4xc5i083.us-south.codeengine.appdomain.cloud/
> Update provider installation code to multiline

- package-lock.json
- package.json
Fixes https://github.com/Qiskit/qiskit.org/issues/3079
> chore(dep): update qiskit web components version

- constants/menuLinks.ts
- pages/learn/index.vue
Replaced links and descriptions for Stack Exchange with Qiskit Support Channels https://qisk.it/support in the footer and https://qiskit.org/learn/ page
Closes https://github.com/Qiskit/qiskit.org/issues/3066
Before: 
After:
> Replace StackExchange with Support Channels

- .gitignore
- package-lock.json
- package.json
- vitest.config.ts
This PR configures test coverage reports with [c8 (Vitest's default)](https://vitest.dev/guide/coverage.html) so that [Coveralls](https://coveralls.io/) work with the generated LCOV file.
Closes #3082
> refactor: setup Coveralls in Nuxt 3

- content/providers/hardware.json
- content/providers/multi-platforms.json
- content/providers/primitives.json
- content/providers/quick-start.json
- https://github.com/HuangJunye/qiskit-providers-quickstart/pull/16
- https://github.com/HuangJunye/qiskit-providers-quickstart/pull/17
- https://github.com/HuangJunye/qiskit-providers-quickstart/pull/18
> Finalise providers quickstart

- nuxt.config.ts
This change makes the production build fetch the content as expected.
> fix: content generation on production

- .github/workflows/deploy.yml
- .github/workflows/verify.yml
- Dockerfile
- package-lock.json
- package.json
This PR updates the project's Node version to v18.
> feat: update to Node 18

- content/ecosystem/members.json
- package-lock.json
- package.json
- tests/providers.spec.ts
This PR adds robust testing to the YAML content files to ensure that the required content for the providers feature exists and is in the expected format.
> test(providers): content files

- components/Ui/UiBasicLink.vue
- components/Ui/UiCodeSnippet.vue
- components/Ui/UiSyntaxHighlight.vue
- composables/useSegment.ts
- middleware/trackPage.global.ts
- nuxt.config.ts
- plugins/segment.client.ts
- plugins/trackClick.ts
This PR fixes the issues with Segment during SSR, since `window` and `document` (both accessed by Segment) are not available in the server.
It also introduces the **trackClick** directive, similar to Saiba.
> fix(segment): SSR compatibility

- plugins/components.client.ts
This PR fixed the issue where tags where showing unstyled.
Closes #3148
- Added the missing `import "@carbon/web-components/es/components/tag/index.js";`.
- Reorganised imports alphabetically for clarify.
> fix: unstyled tags

- content/ecosystem/members.json
- pages/events/index.vue
Changed the design on the EmptyCards, previously taking up more space than needed, and now they've been adjusted to the right width. 
Changes have been applied to the index.vue file in the events folder. 
@techtolentino contributed to this issue.
Changes have been made around the Ui Card regarding empty events, inside the if-else condition of event cards in index.vue.
As seen in the screenshot, the width is no longer occupying all the screen, it now is the same design as regular events.
> fix: fixed design on emptyCards

- components/Advocates/AdvocatesItemCard.vue
If advocates slack handle not provided, hide the slack icon and `@` symbol
Resolves #1940
Before 
After
> fix: hide advocate handle if not provided

- components/Learn/LearnExternalRecommendedReadings.vue
- pages/learn/course/basics-quantum-information.vue
- Add missing space to pages/learn/course/basics-quantum-information.vue
- Closes #3211
> Fix missing spaces in External Recommended readings

- package-lock.json
- package.json
This PR updates various dependencies:
- @carbon/styles
- @ibm/plex
- @types/node
- @typescript-eslint/parser
- eslint-plugin-vue
> chore: dependencies updates

- components/Learn/LearnCoursePagesSection.vue
Fixes #3226 
updated `sizes` props after seeing that image sizes weren't available 
https://qiskit-org-pr-3227.dcq4xc5i083.us-south.codeengine.appdomain.cloud/learn/course/basics-quantum-information/
(showing before and after)
https://github.com/Qiskit/qiskit.org/assets/6276074/00455fb4-bab0-480d-81aa-395ea7a68544
> fix(img): update preview nuxt-img props

- constants/summerSchool2023Content.ts
- pages/events/summer-school-2023.vue
Closes #3231 
https://qiskit-org-pr-3250.dcq4xc5i083.us-south.codeengine.appdomain.cloud/events/summer-school-2023
- enable CTAs
- add links
- remove unused CSS
> feat(qgss23): enable registration CTAs

- content/qamp/qamp-projects.json
- hooks/qamp-cohorts-conversion-utils.ts
- hooks/qamp-participants-conversion-utils.ts
- hooks/qamp-projects-conversion-utils.ts
- hooks/update-advocates.ts
- hooks/update-qamp-projects.ts
- nuxt.config.ts
- tests/hooks/qamp-cohorts-conversion-utils.spec.ts
- tests/hooks/qamp-participants-conversion-utils.spec.ts
- tests/hooks/qamp-projects-conversion-utils.spec.ts
- types/qamp.ts
This PR implements the fetching and conversion of the QAMP data from Airtable.
Part of #3194
Since the data from the "Projects" table references data from the "Cohorts" and "Participants" tables, we needed to create classes with methods to fetch that data as well. They are all very similar in implementation to what we already had in place for "Advocates" and "Events".
We've also added some tests for the new classes.
- Start with the **types/qamp.ts** file to get an idea of the shape of the QAMP objects.
- Check **content/qamp/qamp-projects.json** to see an example of the fetched and converted QAMP data.
- See the **nuxt.config.ts** that now also starts the fetching of the QAMP projects data.
- Check the **hooks/update-qamp-projects.ts** file.
- You can also see the small type improvement …
> feat(qamp): fetch data

- constants/summerSchool2023Content.ts
- pages/events/summer-school-2023.vue
Closes #3255 
Added link back to research blog
https://qiskit-org-pr-3256.dcq4xc5i083.us-south.codeengine.appdomain.cloud/events/summer-school-2023
https://github.com/Qiskit/qiskit.org/assets/6276074/60040800-df53-4fce-b02b-dcceb9565f65
> feat(qgss23): add research blog link

- pages/learn/course/algorithm-design.vue
On [this issue](https://github.ibm.com/IBM-Q-General/user-feedback/issues/9#issue-34253208) an update of the Qiskit Runtime Overview link is required. This PR updates it
> feat(learn): updates qiskit runtime overview link

- constants/summerSchool2023Content.ts
- pages/events/summer-school-2023.vue
Disable the registration CTA
- Disables the CTA
- Changes the text to "General Registration June 1, 9AM EST"
- Adapts the with of the CTA to fit the content
https://github.com/Qiskit/qiskit.org/assets/17231966/9dcdc0a3-891d-4f68-b764-e9653eedad27
> feat(qgss23): disable register cta

- pages/learn/course/introduction-course.vue
Fixed typo "focussing" to "focusing" in Introduction to Quantum Computing
https://qiskit.org/learn/course/introduction-course/
> Fixed typo "focussing" to "focusing" in Introduction to Quantum Computing course

- assets/scss/_typography.scss
- pages/events/summer-school-2023.vue
Updates de text on the header
- Updates the content on the first paragraph on the header with the requested text
- Adds `font-weight` to `<b>` to show the bold CSS
> feat(qgss23): Updates header text

- components/Advocates/AdvocatesMeetTheAdvocates.vue
Fix cards layout on the advocates page
From:
to:
> fix(advocates): cards layout

- pages/ecosystem.vue
Reverts Qiskit/qiskit.org#3281
> Revert "feat/ecosystem redesign add filters"

- constants/summerSchool2023Content.ts
- pages/events/summer-school-2023.vue
This PR disables the registration CTA and removes the "Learn more" link that also pointed to the registration page, as requested offline. (CC @y4izus)
This implementation follow's https://github.com/Qiskit/qiskit.org/pull/3258 by @y4izus.
There were [some discussions](https://github.com/Qiskit/qiskit.org/pull/3258/files#r1206698187) last time about the approach of this implementation and it was decided to implement it as-is given that it's an urgent and temporary change.
The path for the preview page is at `/events/summer-school-2023/`.
**Currentl:**
**Changed:**
> feat(qgss23): disable registration CTA

- components/Ecosystem/EcosystemItemCard.vue
- pages/ecosystem.vue
> Refactor ecosystem feat branch

- pages/ecosystem.vue
This PR removes the custom font size for cards titles in the Ecosystem page.
Closes #3261
> feat(ecosystem): remove custom title size

- components/Landing/HeroMoment/LandingHeroMomentComponent.vue
- components/Landing/HeroMoment/LandingHeroMomentGrid.vue
- components/metal/MetalGrid.vue
Just removed all code related to making one of the tiles in the main page link to the metal page.
This partially closes #3289 , the second item in this issue will be approached via the [qiskit web components repo](https://github.com/Qiskit/web-components).
Before:
https://github.com/Qiskit/qiskit.org/assets/108661074/3ec7b196-1e11-4507-863b-5f40718936c6
after:
> Remove moving tile that links to metal page

- components/Ecosystem/EcosystemItemCard.vue
- hooks/ecosystem-conversion-utils.ts
- tests/hooks/ecosystem-conversion-utils.spec.ts
Fixes #3333 
https://qiskit-org-pr-3335.dcq4xc5i083.us-south.codeengine.appdomain.cloud/ecosystem
- during the fetching of members data, convert `null` stars to `0`
https://github.com/Qiskit/qiskit.org/assets/6276074/9f915b65-a63d-4259-bdd3-15568abc2736
> [ecosystem]: convert stars count

- content/providers/quick-start/data.yaml
Show IBM Quantum after Qiskit on the list of providers
> feat(landing): Show IBM Quantum after Qiskit on the list of providers

- package-lock.json
- package.json
Upgrades qiskit web components package
> Upgrades qiskit web components

- pages/ecosystem.vue
Instead of showing the projects that match all categories selected in the filter, show the projects that match at least one of the selected categories.
Closes #3353
Co-authored-by: @techtolentino
> feat(ecosystem): 3353 filter matching

- components/Ui/UiCard.vue
- pages/events/summer-school-2023.vue
Fixes #3330 
- update card image container style for smaller breakpoints 
- add specific styles to improve the summer school 2023 event card
https://qiskit-org-pr-3356.dcq4xc5i083.us-south.codeengine.appdomain.cloud/events/
https://qiskit-org-pr-3356.dcq4xc5i083.us-south.codeengine.appdomain.cloud/events/summer-school-2023
https://github.com/Qiskit/qiskit.org/assets/6276074/b9859c72-1c2a-49f4-8036-66150cbb27f1
> fix(ui-card): improve responsive cropping

- constants/summerSchool2023Content.ts
- pages/events/summer-school-2023.vue
This PR reverts changes made in PR  #3310. Closes #3362 .
May I suggest maybe changing the text in the button to something like "last chance to register!" ?
⚠️ **IMPORTANT: DO NOT MERGE UNTIL JUNE 28TH!** ⚠️
> Reactivate Registration button in QGSS 2023

- pages/advocates.vue
- pages/ecosystem.vue
- pages/events/fall-fest.vue
- pages/events/index.vue
- pages/events/seminar-series.vue
- pages/events/summer-school-2022.vue
- pages/events/summer-school-2023.vue
- pages/index.vue
- pages/learn/course/algorithm-design.vue
- pages/learn/course/basics-quantum-information.vue
- pages/learn/course/fundamentals-quantum-algorithms.vue
- pages/learn/course/games-and-demos.vue
- pages/learn/course/introduction-course.vue
- pages/learn/course/legacy-content.vue
- pages/learn/course/machine-learning-course.vue
- pages/learn/course/multiple-qubits-and-entanglement.vue
- pages/learn/course/prerequisites.vue
- pages/learn/course/quantum-algorithms-for-applications.vue
- pages/learn/course/quantum-computing-labs.vue
- pages/learn/course/quantum-hardware-circuits.vue
- pages/learn/course/quantum-hardware-pulses.vue
- pages/learn/course/quantum-protocols-and-quantum-algorithms.vue
- pages/learn/course/quantum-states-and-qubits.vue
- pages/learn/index.vue
- pages/learn/summer-school/introduction-to-quantum-computing-and-quantum-hardware-2020.vue
- pages/learn/summer-school/quantum-computing-and-quantum-learning-2021.vue
- pages/learn/summer-school/quantum-simulation-summer-school-2022.vue
- pages/metal.vue
- pages/providers.vue
Resolves #3188 
Using `useSeoMeta` composable for the following pages:
- review use of composable
- review copy updates
- feel free to use a SEO Meta Tag extension checker like this [one](https://chrome.google.com/webstore/detail/meta-seo-inspector/ibkclpciafdglkjkcibmohobjkcfkaef) to verify 
**Homepage BEFORE**
**Homepage AFTER**
<br/>
<br/>
**Providers page BEFORE**
**Providers page AFTER**
<br/>
<br/>
**Course page BEFORE**
**Course page AFTER**
[seo-meta_improvements_screenshots.zip](https://github.com/Qiskit/qiskit.org/files/12007273/seo-meta_improvements_screenshots.zip)
> [seo] optimize titles and descriptions

- components/Layout/Banner/LayoutBannerNewLearningPlatform.vue
- layouts/default-max.vue
- layouts/default.vue
- plugins/components.client.ts
Fix https://github.com/Qiskit/qiskit.org/issues/3410
Adds and styles the banner to announce the new learning platform
Check that the banner is working across the pages under this repo. It is not implemented on the Metal and Error pages because they are not related with Learning
> feat(general): add banner to announce new learning platform

- components/Learn/LearnMegaMenu.vue
It will fix Qiskit/platypus#2151
Removes shors tutorial from Mega Menu.
> Removed shor's tutorial (broken link) from LearnMegaMenu.vue

- components/Layout/Footer/LayoutFooter.vue
Closes #3433 
- removed Learn section and child links
- updated grid class to adjust to new empty space 
https://qiskit-org-pr-3444.dcq4xc5i083.us-south.codeengine.appdomain.cloud/
> feat(footer): remove learn section

- package-lock.json
- package.json
Closes #3451 
https://qiskit-org-pr-3452.dcq4xc5i083.us-south.codeengine.appdomain.cloud/
> chore(dependencies): update qiskit-web-components version

- components/Learn/LearnStartLearning.vue
This PR updates the text of the "Classical Simulators" in the **learn** page.
Closes #3479
> fix(learn): text in "Classical Simulators" card

- package-lock.json
- package.json
Upgrades @qiskit/web-components to fix the Documentation > API Reference link on the top navbar
> feat(navbar): update documentation link

- pages/ecosystem.vue
Adds segment tracking to qiskit.org/ecosystem, specifically
- filters
- search
- sorting
> Add segment tracking to ecosystem page

- components/LearnCourse/LearnCourse.vue
- pages/index.vue
- pages/learn/index.vue
Closes #3555
- Content of the notifications bar on the top of the qiskit.org page updated.
- Content of the banner on the announcement section of the qiskit.org page updated.
- Content of the banner on the announcement section of the qiskit.org/learn page updated.
- Content of the notifications bar on the top of the qiskit.org/course/introduction-course page updated.
> banners content updated

- components/LearnCourse/LearnCourse.vue
- components/OneXP/OneXPPageSection.vue
- pages/index.vue
- pages/learn/index.vue
- Updated the links in banners and notification bars so they point to the corresponding sites.
> Update banners content

- package-lock.json
- package.json
Fix vulnerabilities with npm audit fix
> Fix vulnerabilities with npm audit fix

- hooks/fall-fest-extension-event-conversion.utils.ts
- hooks/fall-fest-partner-event-conversion.utils.ts
- package-lock.json
- package.json
This reverts commit 449f78477c29f04a4628eb04b773231657f4b825 which breaks the local development environment.
> Revert "chore(deps-dev): bump nuxt-schema-org from 2.2.0 to 3.3.2
